// Real rendered Help with local resources; no Chrome API doubles required.
import {createRequire} from 'node:module';import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright'),root=new URL('../account-id-tool/',import.meta.url).pathname,out=process.env.GATHER_BROWSER_ARTIFACTS||new URL('../../artifacts/browser-help/',import.meta.url).pathname;
await fs.mkdir(out,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+new URL(req.url,'http://fixture').pathname);assert.ok(file.startsWith(root));res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.GATHER_CHROMIUM_PATH||'/usr/lib/chromium/chromium',headless:true,chromiumSandbox:true}),page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[],requests=[],passed=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
try{
 await page.goto(origin+'/help.html');await page.getByText('Help · 1.8.15 RC',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.activeElement.id),'helpSearch');assert.equal(await page.locator('article').count(),15);passed.push('Shared Help presents the current version and focuses its search field.');
 await page.locator('#helpSearch').fill('black redaction');assert.ok(await page.locator('#edit').isVisible());assert.ok(await page.locator('article:visible').count()<15);await page.keyboard.press('Escape');assert.equal(await page.locator('article:visible').count(),15);await page.locator('#helpSearch').fill('no-matching-fictional-topic');assert.ok(await page.locator('#noAnswers').isVisible());await page.locator('#clearSearch').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'helpSearch');passed.push('Search, no-match state, Clear and Escape work without saving the search.');
 await page.locator('#helpSearch').fill('lookup');await page.locator('nav').getByText('Privacy',{exact:true}).click();assert.equal(await page.locator('#helpSearch').inputValue(),'');assert.equal(await page.evaluate(()=>document.activeElement.id),'privacy');assert.ok(await page.locator('#privacy').isVisible());passed.push('Topic navigation clears filters and moves keyboard focus to its answer.');
 await page.goto(origin+'/help.html');await page.screenshot({path:path.join(out,'help-desktop.png')});await page.setViewportSize({width:400,height:800});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'help-narrow.png')});assert.ok(requests.every(u=>u.startsWith(origin+'/')));assert.equal(await page.evaluate(()=>localStorage.length),0);assert.equal((await page.evaluate(()=>indexedDB.databases())).length,0);assert.deepEqual(errors,[]);passed.push('Help reflows at 400px and reads no case data, creates no storage, makes no external request and throws no page error.');
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify({status:'passed',kind:'rendered-local-help',passed,errors},null,2));console.log('PASS: '+passed.length+' Help groups.');
}finally{await browser.close();server.close();}
