// Actual rendered product modules + native canvas/IndexedDB. Chrome extension APIs
// are controlled doubles: this is NOT native extension/activeTab acceptance.
import {createRequire} from 'node:module';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const {chromium}=createRequire(import.meta.url)('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../account-id-tool'),artifacts=process.env.GATHER_BROWSER_ARTIFACTS||path.resolve(root,'../../artifacts/browser-case');await fs.mkdir(artifacts,{recursive:true});await fs.rm(path.join(artifacts,'results.json'),{force:true});
const server=http.createServer(async(req,res)=>{try{if(req.url==='/fixture'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><style>html{scroll-behavior:smooth}body{margin:0;font:24px sans-serif;background:#eef4ef}header{position:sticky;top:0;background:#17684b;color:white;padding:20px}.block{height:750px;padding:20px}</style><header>Northbridge — fictional fixture</header><div class="block">Alex Example · October review</div><div class="block">Second section — deterministic data</div><div class="block">Third section — no real people</div>');return;}const name=decodeURIComponent(new URL(req.url,'http://test').pathname).slice(1)||'workspace.html';const full=path.resolve(root,name);if(!full.startsWith(root+path.sep))throw new Error('path');const data=await fs.readFile(full);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'})[path.extname(full)]||'application/octet-stream');res.end(data);}catch{res.writeHead(404);res.end('missing');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,profile=await fs.mkdtemp(path.join(os.tmpdir(),'gather-rendered-'));let context,source;
const events=[];
try{
  context=await chromium.launchPersistentContext(profile,{executablePath:process.env.GATHER_CHROMIUM_PATH||'/usr/lib/chromium/chromium',chromiumSandbox:true,headless:true,viewport:{width:1280,height:800}});
  await context.exposeBinding('__gatherInject',async(_,{fn,args})=>source.evaluate(({fn,args})=>{const f=(0,eval)('('+fn+')');return f(...args);},{fn,args}));
  await context.exposeBinding('__gatherScreenshot',async()=>{await source.bringToFront();return 'data:image/png;base64,'+(await source.screenshot()).toString('base64');});
  await context.addInitScript(({origin})=>{
    if(location.pathname==='/fixture')return;origin=location.origin;
    const event=()=>{const listeners=new Set();return {addListener:f=>listeners.add(f),removeListener:f=>listeners.delete(f),emit:(...args)=>{for(const f of listeners)f(...args);}};};
    const changed=event(),area=prefix=>({async get(key){const all=JSON.parse(localStorage.getItem(prefix)||'{}');return key===null?all:{[key]:all[key]};},async set(values){const all=JSON.parse(localStorage.getItem(prefix)||'{}'),changes={};for(const [key,value]of Object.entries(values)){changes[key]={oldValue:all[key],newValue:value};all[key]=value;}localStorage.setItem(prefix,JSON.stringify(all));changed.emit(changes,prefix==='local'?'local':'session');},async remove(key){const all=JSON.parse(localStorage.getItem(prefix)||'{}');delete all[key];localStorage.setItem(prefix,JSON.stringify(all));},async setAccessLevel(){}});
    const readTabs=()=>JSON.parse(localStorage.getItem('mockTabs')||'[]'),writeTabs=rows=>localStorage.setItem('mockTabs',JSON.stringify(rows));
    const tabs={onCreated:event(),onRemoved:event(),onActivated:event(),onUpdated:event(),onReplaced:event(),async query(q){return readTabs().filter(t=>(!q?.active||t.active)&&(!q?.windowId||t.windowId===q.windowId));},async get(id){const t=readTabs().find(t=>t.id===id);if(!t)throw new Error('No tab');return t;},async getCurrent(){return location.pathname==='/workspace.html'&&!location.search?{id:99}:undefined;},async create(options){const t={id:Math.floor(Math.random()*1e8),windowId:1,active:options.active!==false,...options};const rows=readTabs();if(t.active)rows.forEach(r=>r.active=false);rows.push(t);writeTabs(rows);tabs.onCreated.emit(t);return t;},async update(id,options){const rows=readTabs(),t=rows.find(t=>t.id===id);if(options.active)rows.forEach(r=>r.active=false);Object.assign(t,options);writeTabs(rows);tabs.onUpdated.emit(id,options,t);return t;},async remove(id){writeTabs(readTabs().filter(t=>t.id!==id));tabs.onRemoved.emit(id);},async captureVisibleTab(){return __gatherScreenshot();}};
    const windows={onRemoved:event(),async getCurrent(){return {id:location.pathname==='/capture.html'?2:1};},async get(id){if(id===2&&localStorage.getItem('captureOpen')!=='true')throw new Error('No window');return {id};},async update(){return {};},async create({url}){localStorage.setItem('captureOpen','true');window.open(url,'gather-test-capture');return {id:2};}};
    let downloadId=1;const downloads={onChanged:event(),async download(options){if(localStorage.getItem('denyDownloads')==='true')throw new Error('Folder access denied (test double)');const n=downloadId++;localStorage.setItem('lastDownload',JSON.stringify(options));return n;},async search({id}){return [{id,state:'complete'}];}};
    globalThis.chrome={runtime:{id:'gather-test',getURL:f=>origin+'/'+f,onMessage:event(),onInstalled:event(),onStartup:event(),async sendMessage(m){try{if(m.type==='history.flush'){await (await import(origin+'/batches.js')).saveBatch(m.batch);return {ok:true};}if(m.type==='capture.start')return await (await import(origin+'/capture-launch.js')).launchCapture(m);if(m.type==='capture.finished')return await (await import(origin+'/capture-launch.js')).finishCapture(m.launchId);if(m.type.startsWith('quick.'))return await (await import(origin+'/quick-worker.js')).handleQuick(m);return await (await import(origin+'/workspace-store.js')).handleWorkspace(m);}catch(e){return {error:e.message};}}},storage:{local:area('local'),session:area('session'),onChanged:changed},tabs,windows,downloads,scripting:{async executeScript({func,args=[]}){return [{result:await __gatherInject({fn:func.toString(),args}),documentId:'fixture-document'}];}},contextMenus:{update:async()=>{}},action:{setBadgeText:async()=>{}},sidePanel:{open:async()=>{}}};
    globalThis.__seedTabs=rows=>writeTabs(rows);
    addEventListener('storage',event=>{if(['local','session'].includes(event.key)){const before=JSON.parse(event.oldValue||'{}'),after=JSON.parse(event.newValue||'{}'),diff={};for(const key of new Set([...Object.keys(before),...Object.keys(after)]))if(JSON.stringify(before[key])!==JSON.stringify(after[key]))diff[key]={oldValue:before[key],newValue:after[key]};changed.emit(diff,event.key);}});
  },{origin});
  source=await context.newPage();await source.goto(origin+'/fixture');const page=await context.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.stack);});await page.goto(origin+'/workspace.html');
  await page.evaluate(({origin})=>__seedTabs([{id:10,windowId:1,url:origin+'/fixture',title:'Fictional public evidence',active:true}]),{origin});
  await page.getByRole('button',{name:'New case',exact:true}).click();await page.getByLabel('Case name').fill('TEST-28175 — Stadium Altercation');
  await page.getByText('Add intake to prepare searches (optional)',{exact:true}).click();
  await page.getByLabel('Paste intake for local review').fill('SOC: Alex Example (16, grade 10); Robin Sample (15, grade 9)\nPeer: Jordan Example\nSchools: Northbridge School; Lakeside School\nUsername: alex.example\nTerms: stadium\nContact: private@example.test');
  await page.getByRole('button',{name:'Review extracted fields'}).click();assert.equal(await page.locator('.case-review-row').count(),12);
  await page.getByLabel('Paste intake for local review').press('End');await page.getByLabel('Paste intake for local review').press('Space');assert.equal(await page.getByRole('button',{name:'Create case',exact:true}).isDisabled(),true);assert.equal(await page.locator('.case-review-row').count(),0);await page.getByRole('button',{name:'Review extracted fields'}).click();
  assert.equal(await page.getByRole('checkbox',{name:'Retain Contact'}).isChecked(),false);
  await page.getByRole('textbox',{name:'Reviewed value'}).nth(3).fill('Robin Corrected');await page.getByRole('checkbox',{name:'Retain Terms'}).uncheck();
  await page.screenshot({path:path.join(artifacts,'case-start-review.png'),fullPage:true});await page.getByRole('button',{name:'Create case',exact:true}).click();await page.getByRole('heading',{name:'Initial scan',exact:true}).waitFor();await page.getByText(/Scan queue ·/).click();await page.locator('.case-queue-row').first().waitFor();
  const created=await page.evaluate(async()=>{const state=(await chrome.runtime.sendMessage({type:'workspace.state'})).state,bundle=await (await import('./capture-store.js')).snapshotCaptureBundle();return {state,subjects:bundle.subjects,session:await chrome.storage.session.get(null)};});const pid=created.state.projects[0].id,sid=created.state.activeScanId,alex=created.subjects.find(s=>s.roleId==='SOC-01');assert.ok(alex);assert.deepEqual(created.subjects.map(s=>s.roleId).sort(),['PEER-01','SOC-01','SOC-02']);assert.doesNotMatch(JSON.stringify({state:created.state,subjects:created.subjects}),/Alex Example|Robin Corrected|private@example/);assert.match(JSON.stringify(created.session),/Robin Corrected/);events.push('Actual Case Start review corrects a field, rejects a term, excludes private contact and commits three roles; ephemeral names absent from durable context.');
  await page.locator('.case-queue-row').first().getByRole('button',{name:'Launch ↗',exact:true}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('local'))['gather.workspace.v1'].research.queue[0].status==='launched');
  const launched=await page.evaluate(async()=>{const state=(await chrome.runtime.sendMessage({type:'workspace.state'})).state;return {state,tabs:await chrome.tabs.query({})};});assert.match(launched.tabs.find(t=>t.url?.includes('google.com')).url,/Alex%20Example/);assert.doesNotMatch(JSON.stringify(launched.state),/Alex Example/);assert.equal(launched.state.research.coverage[0].status,'Search launched');events.push('Editable queued search resolves ephemeral values only for launch; no automatic query log is saved; the deliberate plan and coverage record launch.');
  await page.getByText('Coverage · record work and negative results',{exact:true}).click();await page.getByLabel('SOC-01 instagram coverage',{exact:true}).selectOption('Searched — no reliable match');
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('local'))['gather.workspace.v1'].research.coverage.some(c=>c.family==='instagram'&&c.status==='Searched — no reliable match'));
  const sourceSaved=await page.evaluate(async({pid,sid})=>{const tabs=await chrome.tabs.query({}),parent=tabs.find(t=>t.url?.includes('google.com'));await (await import('./tab-context.js')).inheritTabContext({id:10,openerTabId:parent.id});await chrome.tabs.update(10,{active:true});await chrome.runtime.sendMessage({type:'workspace.action',action:{type:'project.create',name:'Southridge',scanName:'Intake'}});const saved=await chrome.runtime.sendMessage({type:'workspace.capture',tabId:10,scanId:sid});if(saved.error)throw new Error(saved.error);return saved;},{pid,sid});assert.equal(sourceSaved.state.items[0].projectId,pid);assert.equal(sourceSaved.state.items[0].filingSubjectId,alex.id);assert.equal(sourceSaved.state.items[0].metadataOnly,true);assert.ok(sourceSaved.state.items[0].evidenceId);events.push('Result opener retains original scan after switching to Southridge; metadata-only save retains role and Evidence ID without image assets.');
  await page.evaluate(scanId=>chrome.runtime.sendMessage({type:'workspace.action',action:{type:'context.select',scanId}}),sid);await page.getByRole('heading',{name:'Initial scan',exact:true}).waitFor();
  await page.getByRole('tab',{name:'Research',exact:true}).click();
  await page.locator('#query').fill('Additional Fictional Alias');
  assert.doesNotMatch(JSON.stringify(await page.evaluate(async()=>({local:await chrome.storage.local.get(null),session:await chrome.storage.session.get(null)}))),/Additional Fictional Alias/);
  await page.locator('#searchForm').getByRole('button',{name:'Search ↗',exact:true}).click();await page.getByText('Search opened. Query not saved in Gather.',{exact:true}).waitFor();
  const manual=await page.evaluate(async()=>({local:await chrome.storage.local.get(null),session:await chrome.storage.session.get(null)}));assert.doesNotMatch(JSON.stringify(manual),/Additional Fictional Alias/);assert.equal(manual.local['gather.workspace.v1'].searches.length,0);
  events.push('Manual searches in Ephemeral Case retain neither draft nor query in local or session storage.');
  const account=await page.evaluate(async sid=>{const {normalizeProfile,applyLookup}=await import('./core.js');const e={...normalizeProfile('instagram.com/fictional_alex'),notes:[],providedIds:[]};applyLookup(e,{id:'9007199254740993123',verifiedAt:1780000000000,displayName:'Similar fictional name',method:'Deterministic test adapter'});const r=await chrome.runtime.sendMessage({type:'workspace.action',action:{type:'item.save',kind:'account',scanId:sid,entry:e}});if(r.error)throw new Error(r.error);return r;},sid);assert.equal(account.state.research.associations.length,0);
  await page.getByRole('tab',{name:'Case',exact:true}).click();
  await page.getByRole('button',{name:'Associate / reject finding'}).click();await page.getByLabel('Finding',{exact:true}).waitFor({timeout:5000}).catch(async e=>{console.error(await page.locator('body').innerText());throw e;});await page.getByLabel('Finding',{exact:true}).selectOption(account.result.id);await page.getByLabel('Analyst decision').selectOption('confirmed');await page.getByLabel('Supporting identifiers / reason').fill('Explicit fictional known profile link');await page.getByRole('button',{name:'Record decision'}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('local'))['gather.workspace.v1'].research.associations.length===1);events.push('Similar account name creates no association; actual review dialog explicitly confirms finding with supporting reason.');
  await page.getByText('Case tools',{exact:true}).click();
  await page.getByRole('button',{name:'Copy role account block'}).click();const block=await page.getByLabel('Clipboard preview').inputValue();assert.match(block,/9007199254740993123/);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();events.push('Clipboard account block preview preserves exact permanent string ID and requires deliberate copy.');
  const screenshot=await page.evaluate(async({sid,alex,origin})=>{const store=await import('./capture-store.js'),state=(await chrome.runtime.sendMessage({type:'workspace.state'})).state;const context=await store.resolveCaptureDestination(state,sid,alex);const pending=await store.beginCapture({context,source:{url:origin+'/fixture',title:'Fictional screenshot'},mode:'visible'});const canvas=document.createElement('canvas');canvas.width=120;canvas.height=80;canvas.getContext('2d').fillRect(0,0,120,80);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const record=await store.completeCapture(pending.id,{assets:[{role:'original',blob}]});const path=(await import('./capture-files.js')).captureExportPath(record);return {record,path};},{sid,alex:alex.id,origin});assert.equal(screenshot.record.context.subjectName,'SOC-01');assert.match(screenshot.path,/SOC-01--/);assert.doesNotMatch(screenshot.path,/Alex|Stadium/);events.push('Visible-image fixture persists in real IndexedDB with stable Evidence ID, role destination and filenames without friendly labels.');
  const derivative=await page.evaluate(async id=>{const store=await import('./capture-store.js'),record=await store.getCapture(id);if(record.included!==false)throw new Error('New capture was silently included');const canvas=document.createElement('canvas');canvas.width=120;canvas.height=80;const ctx=canvas.getContext('2d');ctx.fillStyle='#0000ff';ctx.fillRect(0,0,120,80);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const derived=await store.addCaptureDerivative(id,{blob,parentAssetId:record.assets[0].id,kind:'redacted'});await store.updateCaptureReview(id,{included:true,review:'reviewed'});return {sha:derived.assets.at(-1).sha256,originalSha:record.assets[0].sha256};},screenshot.record.id);
  const sheet=await context.newPage();await sheet.goto(origin+'/evidence.html?scan='+sid);await sheet.locator('.evidence-sheet').waitFor();assert.equal(await sheet.locator('.evidence-sheet').count(),1);await sheet.evaluate(()=>{const download=chrome.downloads.download;chrome.downloads.download=async options=>{globalThis.exportedHTML=await (await fetch(options.url)).text();return download(options);};});await sheet.getByRole('button',{name:'Export review sheet'}).click();await sheet.getByText(/Exported the selected review sheet/).waitFor();const exported=await sheet.evaluate(()=>exportedHTML);assert.match(exported,new RegExp(derivative.sha));assert.ok(!exported.includes(derivative.originalSha));assert.match(exported,/crosswalk/);await sheet.screenshot({path:path.join(artifacts,'evidence-sheet.png'),fullPage:true});await sheet.close();events.push('New captures require explicit inclusion; evidence sheet exports only the selected flattened derivative and a stable Evidence-ID crosswalk, excluding original image bytes/hash.');
  const renamed=await page.evaluate(async id=>{const store=await import('./capture-store.js');await store.renameSubject(id,'Alex Renamed');const b=await store.snapshotCaptureBundle();return {raw:b.subjects.find(s=>s.id===id),session:await chrome.storage.session.get(null)};},alex.id);assert.equal(renamed.raw.name,'SOC-01');assert.match(JSON.stringify(renamed.session),/Alex Renamed/);events.push('Ephemeral friendly-label rename changes session display only; role ID and capture history remain stable.');
  await page.screenshot({path:path.join(artifacts,'case-workspace.png'),fullPage:true});await page.setViewportSize({width:400,height:900});await page.screenshot({path:path.join(artifacts,'case-workspace-narrow.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:1280,height:900});
  const backup=await page.evaluate(async()=>{const mod=await import('./capture-backup.js'),b=(await chrome.runtime.sendMessage({type:'workspace.backup'})).backup,blob=await mod.createFullBackup(b),manifest=await mod.readFullBackup(blob);globalThis.caseBackup=blob;return {manifest:{state:manifest.workspaceBackup.workspace,subjects:manifest.bundle.subjects},size:blob.size};});assert.doesNotMatch(JSON.stringify(backup),/Alex Renamed|Robin Corrected|private@example/);
  const imported=await page.evaluate(async pid=>{const {readFullBackup,stageFullRestore}=await import('./capture-backup.js'),manifest=await readFullBackup(caseBackup),r=await chrome.runtime.sendMessage({type:'workspace.importImages',stageId:await stageFullRestore(manifest)});if(r.error)throw new Error(r.error);const bundle=await (await import('./capture-store.js')).snapshotCaptureBundle();return {state:r.state,bundle:{subjects:bundle.subjects,captures:bundle.captures},map:r.result.idMap};},pid);const importedProject=imported.map[pid],importedSeed=imported.state.research.seeds.find(s=>s.projectId===importedProject&&s.roleId==='SOC-01');assert.ok(importedSeed);assert.ok(imported.bundle.subjects.some(s=>s.id===importedSeed.subjectId&&s.projectId===importedProject));assert.equal(imported.bundle.captures.find(c=>c.projectId===importedProject).subjectId,importedSeed.subjectId);events.push('Full binary backup excludes ephemeral names; merge restore preserves/remaps role, seed, search, finding, association and capture relationships.');
  await page.evaluate(pid=>chrome.storage.session.remove('gather.case.'+pid),pid);await page.reload();await page.getByRole('heading',{name:'Initial scan',exact:true}).waitFor();await page.screenshot({path:path.join(artifacts,'case-workspace-default.png'),fullPage:true});
  const resumed=await page.evaluate(async({pid,sid})=>{const state=(await chrome.runtime.sendMessage({type:'workspace.state'})).state,subjects=await (await import('./capture-store.js')).listSubjects(pid),launch=await chrome.runtime.sendMessage({type:'workspace.launchQueued',id:state.research.queue.find(q=>q.scanId===sid).id});return {subjects,launch};},{pid,sid});assert.equal(resumed.subjects.find(s=>s.id===alex.id).name,'SOC-01');assert.match(resumed.launch.error,/released/);events.push('Simulated browser-session loss releases ephemeral names; durable role evidence survives and searches ask for approved values instead of guessing.');
  // A stale backup guard must reject removal, including when a new source appears.
  const guardCheck=await page.evaluate(async pid=>{const {projectSignature}=await import('./case-close.js'),store=await import('./capture-store.js'),state=(await chrome.runtime.sendMessage({type:'workspace.state'})).state,guard={revision:state.revision,digest:await store.hashBytes(new Blob([projectSignature(await store.snapshotCaptureBundle(),pid)]))};await chrome.runtime.sendMessage({type:'workspace.action',action:{type:'task.create',scanId:state.activeScanId,title:'Later fictional action'}});return chrome.runtime.sendMessage({type:'workspace.closeProject',projectId:pid,guard});},pid);assert.match(guardCheck.error,/changed/);events.push('Close Case refuses a stale backup snapshot after new research is saved.');
  // Cancel while an optional backup download is pending must not delete afterwards.
  await page.getByRole('tab',{name:'Settings',exact:true}).click();
  await page.getByRole('button',{name:'Delete case…'}).click();await page.getByLabel('Type the case name to confirm deletion: TEST-28175 — Stadium Altercation').fill('TEST-28175 — Stadium Altercation');
  await page.evaluate(()=>{const original=chrome.downloads.download;chrome.downloads.download=async options=>{globalThis.backupWaiting=true;await new Promise(r=>globalThis.releaseBackup=r);chrome.downloads.download=original;const id=await original(options);globalThis.backupFinished=true;return id;};});
  await page.getByRole('button',{name:'Back up then delete'}).click();await page.waitForFunction(()=>globalThis.backupWaiting);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(()=>releaseBackup());await page.waitForFunction(()=>globalThis.backupFinished);
  assert.ok(await page.evaluate(async pid=>(await chrome.runtime.sendMessage({type:'workspace.state'})).state.projects.some(p=>p.id===pid),pid));
  await page.getByRole('button',{name:'Delete case…'}).click();await page.getByLabel('Type the case name to confirm deletion: TEST-28175 — Stadium Altercation').fill('TEST-28175 — Stadium Altercation');await page.evaluate(()=>localStorage.setItem('denyDownloads','true'));await page.getByRole('button',{name:'Back up then delete'}).click();await page.getByRole('dialog').getByText(/Folder access denied/).waitFor();assert.ok(await page.evaluate(pid=>JSON.parse(localStorage.getItem('local'))['gather.workspace.v1'].projects.some(p=>p.id===pid),pid));events.push('Cancel during a pending optional backup prevents later deletion; denied backup download also leaves the complete project and images intact.');
  await page.evaluate(()=>localStorage.setItem('denyDownloads','false'));await page.getByRole('button',{name:'Back up then delete'}).click();await page.getByRole('dialog').waitFor({state:'detached'});
  const closed=await page.evaluate(async pid=>{const state=(await chrome.runtime.sendMessage({type:'workspace.state'})).state,bundle=await (await import('./capture-store.js')).snapshotCaptureBundle();return {state,captures:bundle.captures,subjects:bundle.subjects,session:await chrome.storage.session.get(null)};},pid);assert.ok(!closed.state.projects.some(p=>p.id===pid));assert.ok(!closed.captures.some(c=>c.projectId===pid));assert.ok(!closed.subjects.some(s=>s.projectId===pid));assert.ok(closed.state.projects.some(p=>p.id===importedProject));events.push('Retry completes private backup download before project, roles, images and session labels are logically removed; other projects remain.');
  // Clear local history with popup and full tool open. Both must discard visible private text.
  const historySeed=await page.evaluate(async()=>{const b={id:'privacy-fictional',title:'Fictional recent lookup',entries:[{url:'https://www.instagram.com/alex.example/',id:'9007199254740993123',status:'resolved'}]};await (await import('./batches.js')).saveBatch(b);await chrome.storage.local.set({'gather.quick':{batchId:b.id,input:'fictional quick draft'},'gather.draft':'fictional full draft','gather.archive.privacy':{'gather.batch.old':b,'gather.prefs':{autoCopy:false}}});return b;});
  const full=await context.newPage(),popup=await context.newPage();await full.goto(origin+'/index.html?batch=privacy-fictional');await full.locator('#resultsView').waitFor();await popup.goto(origin+'/popup.html');await popup.locator('#quickLinks').waitFor();
  await page.getByRole('button',{name:'Clear recent lookup history…',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();assert.ok(await page.evaluate(async()=> (await import('./batches.js')).loadBatch('privacy-fictional')));
  await page.getByRole('button',{name:'Clear recent lookup history…',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Clear recent lookup history',exact:true}).click();
  await full.locator('#inputView').waitFor();await popup.waitForFunction(()=>document.getElementById('quickLinks').value==='');assert.equal(await full.locator('#accountList').innerText(),'');
  const privacyState=await page.evaluate(async()=>({local:await chrome.storage.local.get(null),bundle:await (await import('./capture-store.js')).snapshotCaptureBundle()}));assert.equal(privacyState.local['gather.batch.privacy-fictional'],null);assert.deepEqual(privacyState.local['gather.archive.privacy'],{'gather.prefs':{autoCopy:false}});assert.ok(privacyState.bundle.captures.some(c=>c.projectId===importedProject));
  await full.close();await popup.close();assert.equal(await page.evaluate(async()=> (await import('./batches.js')).loadBatch('privacy-fictional')),null);events.push('Clear history Cancel preserves data; confirmed clear removes open full-tool and popup contents, draft/archive copies and survives page-close flush, while restored case images remain.');
  // Delete a restored case without creating another copy; other case survives.
  const importedScan=imported.state.scans.find(s=>s.projectId===importedProject).id;
  await page.evaluate(scanId=>chrome.runtime.sendMessage({type:'workspace.action',action:{type:'context.select',scanId}}),importedScan);
  await page.getByRole('button',{name:'Delete case…'}).waitFor();await page.getByRole('button',{name:'Delete case…'}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();
  const downloadsBefore=await page.evaluate(()=>localStorage.getItem('lastDownload'));
  await page.getByRole('button',{name:'Delete case…'}).click();await page.getByRole('button',{name:'Delete without backup'}).click();await page.getByRole('dialog').getByText(/Enter the displayed case name/).waitFor();
  const currentName=imported.state.projects.find(p=>p.id===importedProject).name;await page.getByLabel('Type the case name to confirm deletion: '+currentName).fill(currentName);
  await page.setViewportSize({width:400,height:900});await page.screenshot({path:path.join(artifacts,'privacy-delete-dialog.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.getByRole('button',{name:'Delete without backup'}).click();await page.getByRole('dialog').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>localStorage.getItem('lastDownload')),downloadsBefore);
  const afterDirect=await page.evaluate(async()=>({state:(await chrome.runtime.sendMessage({type:'workspace.state'})).state,bundle:await (await import('./capture-store.js')).snapshotCaptureBundle()}));assert.ok(!afterDirect.state.projects.some(p=>p.id===importedProject));assert.equal(afterDirect.bundle.assets.length,0);assert.ok(afterDirect.state.projects.some(p=>p.name==='Southridge'));
  await page.screenshot({path:path.join(artifacts,'privacy-workspace-narrow.png'),fullPage:true});events.push('Red Delete case actions require the typed name; Cancel preserves data, Delete without backup removes originals/derivatives without a download and leaves Southridge. Dialog fits 400 px.');
  await page.goto(origin+'/popup.html');await page.waitForFunction(()=>document.activeElement?.id==='quickLinks');assert.equal(await page.locator('#captureTools').isVisible(),false);events.push('After Close Case, Quick Lookup still opens focused and independent of projects.');
  await page.evaluate(async()=>{const core=await import('./core.js');const ready=Array.from({length:5},(_,i)=>({...core.normalizeProfile('instagram.com/fictional_'+i),id:'900719925474099312'+i,status:'resolved',verifiedAt:1780000000000,verificationSource:'live',notes:[],providedIds:[]}));const gone=name=>{const e={...core.normalizeProfile('youtube.com/@'+name),notes:[],providedIds:[]};core.applyLookup(e,core.extractId('<script>var ytInitialData = {"alerts":[{"alertRenderer":{"type":"ERROR","text":{"simpleText":"This channel does not exist."}}}]};</script>',e));return e;};const entries=[gone('old-one'),...ready,{...core.normalizeProfile('instagram.com/markup_failure'),status:'error',message:'Fixture markup could not be determined'},gone('old-two')],batch={id:'fictional-account-states',createdAt:1780000000000,updatedAt:1780000000000,entries};await chrome.storage.local.set({'gather.batch.fictional-account-states':batch,'gather.quick':{batchId:batch.id,input:''}});});await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#quickList .account-row').length===8);const rows=await page.locator('#quickList .account-row').allTextContents();assert.ok(rows.slice(6).every(text=>text.includes('Gone')));assert.equal(await page.locator('#quickList .account-row').nth(6).locator('.id-line').count(),0);assert.equal(await page.getByText('Could not determine — review',{exact:true}).count(),1);assert.match(await page.locator('#quickSummary').textContent(),/5 accounts ready.*2 gone.*1 could not/);await page.screenshot({path:path.join(artifacts,'account-state-popup.png'),fullPage:true});events.push('Actual popup renders five usable accounts first, one technical review group, and two quiet gone accounts last without empty ID fields.');
  assert.deepEqual(errors,[]);console.log('PASS R3 rendered Chromium journey with Chrome API doubles\n'+events.map((e,i)=>`${i+1}. ${e}`).join('\n'));await fs.writeFile(path.join(artifacts,'results.json'),JSON.stringify({kind:'rendered-browser-with-extension-api-doubles',nativeExtension:false,passed:events,errors},null,2));
}finally{await context?.close();server.close();await fs.rm(profile,{recursive:true,force:true});}
