// Real installed Edge, real local storage/IndexedDB/clipboard, fictional intercepted
// web pages. Source launch is scripted here; physical context-menu checks are separate.
import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const {chromium}=createRequire(import.meta.url)('playwright');
const root=path.resolve(process.env.GATHER_EXTENSION_ROOT||new URL('../account-id-tool/',import.meta.url).pathname),out=process.env.GATHER_BROWSER_ARTIFACTS||new URL('../../artifacts/browser-r6/',import.meta.url).pathname;
const temporary=await fs.mkdtemp(path.join(os.tmpdir(),'gather-r6-'));await fs.mkdir(out,{recursive:true});
execFileSync('python3',['-c',`from PIL import Image,ImageDraw\nfrom pathlib import Path\np=Path(${JSON.stringify(temporary)})\nfor ext in ['png','jpg','webp','avif','gif']:\n im=Image.new('RGBA',(160,100),(0,90,210,0 if ext=='png' else 255));d=ImageDraw.Draw(im);d.rectangle((10,10,90,70),fill=(220,30,40,255));\n if ext in ['jpg','gif']: im=im.convert('RGB')\n im.save(p/('fixture.'+ext))\nim=Image.new('RGB',(4096,2048),'blue');im.save(p/'large.png')`]);
const images=new Map();for(const ext of ['png','jpg','webp','avif','gif'])images.set('/fixture.'+ext,{bytes:await fs.readFile(path.join(temporary,'fixture.'+ext)),type:({'jpg':'image/jpeg'})[ext]||'image/'+ext});images.set('/large.png',{bytes:await fs.readFile(path.join(temporary,'large.png')),type:'image/png'});
const passed=[],errors=[],requests=[],canaries=['PRIVATE_CASE_CANARY_84217','PRIVATE_SOC_CANARY_912','PRIVATE_NOTE_CANARY_ABC'];let contexts=[],context,api,base,releaseDelayed;
const headed=process.env.GATHER_R6_HEADED==='1';
const manifest=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8'));
async function open(profile){
 const ctx=await chromium.launchPersistentContext(path.join(temporary,profile),{executablePath:process.env.GATHER_CHROMIUM_PATH,headless:!headed,chromiumSandbox:true,acceptDownloads:true,viewport:{width:1280,height:900},ignoreDefaultArgs:['--disable-extensions'],args:['--disable-extensions-except='+root,'--load-extension='+root]});contexts.push(ctx);ctx.setDefaultTimeout(15000);ctx.on('weberror',event=>errors.push(event.error().message));
 await ctx.route(/^https?:\/\//,async route=>{
  const request=route.request(),url=new URL(request.url());requests.push({url:request.url(),method:request.method(),body:request.postData(),headers:request.headers()});
  if(url.pathname==='/delay.png')await new Promise(resolve=>releaseDelayed=resolve);
  if(url.pathname==='/denied.png'){await route.fulfill({status:403,body:'Access denied'});return;}
  const image=images.get(url.pathname==='/delay.png'?'/fixture.png':url.pathname);
  if(image){await route.fulfill({contentType:image.type,body:image.bytes,headers:url.hostname==='blocked.example.test'?{'Access-Control-Allow-Origin':'https://wrong.example.test'}:{'Access-Control-Allow-Origin':'*'}});return;}
  let data={username:'alex.example',id:'9007199254740993123',full_name:'Alex Example'};
  if(url.hostname.includes('tiktok'))data={itemInfo:{itemStruct:{id:'123456789',author:{uniqueId:'alex.example',id:'9007199254740993123',nickname:'Alex Example'}}}};
  if(url.pathname.includes('/reel/AB_example'))data={shortcode:'AB_example',owner:{username:'alex.example',id:'9007199254740993123',full_name:'Alex Example'}};
  if(url.hostname.includes('threads'))data={code:'AB_example',user:{username:'alex.example',id:'9007199254740993123'}};
  if(url.hostname.includes('youtube'))data={videoDetails:{videoId:'ABCDEFGHIJK',channelId:'UC1234567890123456789012',author:'Example Channel'}};
  if(url.hostname.includes('facebook'))data={video_id:'123456789',owner:{__typename:'Page',id:'9007199254740993123',name:'Example Page'}};
  await route.fulfill({contentType:'text/html',body:'<!doctype html><title>Fictional image fixture</title><script type="application/json">'+JSON.stringify(data)+'</script><meta charset="utf-8"><style>body{min-height:2400px;background:white}</style><h1>Fictional public fixture</h1><img id="image" src="/fixture.png" width="160" height="100">'});
 });
 let worker=ctx.serviceWorkers().find(w=>w.url().endsWith('/background.js'));worker||=await ctx.waitForEvent('serviceworker',{predicate:w=>w.url().endsWith('/background.js')});
 const origin='chrome-extension://'+new URL(worker.url()).host,page=await ctx.newPage();await page.goto(origin+'/workspace.html');await page.locator('.layout:not([inert])').waitFor();return {ctx,worker,page,base:origin};
}
const group=(message)=>{passed.push(message);console.log('PASS '+message);};
try{
 ({ctx:context,page:api,base}=await open('profile-a'));
 const ids=await api.evaluate(async canaries=>{
  const send=action=>chrome.runtime.sendMessage({type:'workspace.action',action});const a=await send({type:'project.create',name:canaries[0],scanName:'October review'});if(a.error)throw Error(a.error);
  const store=await import('./capture-store.js'),subject=await store.createSubject({projectId:a.result.id,name:canaries[1]});await store.selectSubject(a.result.scanId,subject.id,a.result.id);
  await send({type:'item.save',kind:'note',scanId:a.result.scanId,title:'Fictional note',body:canaries[2]});
  const b=await send({type:'project.create',name:'Southridge',scanName:'Review'});await send({type:'context.select',scanId:a.result.scanId});return {project:a.result.id,scan:a.result.scanId,subject:subject.id,otherScan:b.result.scanId};
 },canaries);
 const lookupPage=await context.newPage(),lookupApi=await context.newPage();await lookupApi.goto(base+'/popup.html');
 for(const [url,expected] of [
  ['https://www.tiktok.com/@alex.example/video/123456789?tracking=fictional','https://www.tiktok.com/@alex.example'],
  ['https://www.instagram.com/reel/AB_example/?tracking=fictional','https://www.instagram.com/alex.example/'],
  ['https://www.threads.com/@alex.example/post/AB_example','https://www.threads.com/@alex.example'],
  ['https://www.youtube.com/watch?v=ABCDEFGHIJK&tracking=fictional','https://www.youtube.com/channel/UC1234567890123456789012'],
  ['https://www.facebook.com/reel/123456789/?tracking=fictional','https://www.facebook.com/profile.php?id=9007199254740993123']]){
  await lookupPage.goto(url);const result=await lookupApi.evaluate(async url=>{
   const tab=(await chrome.tabs.query({})).find(t=>t.url===url),before=await chrome.runtime.sendMessage({type:'quick.state'});
   const started=await chrome.runtime.sendMessage({type:'quick.start',input:url,currentTabId:tab.id,historyEpoch:before.historyEpoch});if(started.error)throw Error(started.error);
   for(let i=0;i<300;i++){const state=await chrome.runtime.sendMessage({type:'quick.state'});if(!state.busy&&state.batch?.id===started.batch.id&&state.batch.entries.every(e=>!['ready','loading'].includes(e.status)))return state.batch.entries[0];await new Promise(r=>setTimeout(r,50));}throw Error('Lookup timed out');
  },url);assert.equal(result.url,expected,JSON.stringify(result));assert.equal(result.id,url.includes('youtube')?'UC1234567890123456789012':'9007199254740993123');assert.equal(result.sourcePageUrl,url);
 }
 const full=await context.newPage();await full.goto(base+'/index.html');await full.locator('#links').fill('https://www.tiktok.com/@alex.example/video/123456789');await full.locator('#links').press('Shift+Enter');assert.ok((await full.locator('#links').inputValue()).endsWith('\n'));await full.evaluate(()=>{globalThis.testBatchIds=new Set();chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local')for(const key of Object.keys(changes))if(key.startsWith('gather.batch.')&&changes[key].newValue?.id)testBatchIds.add(key);});});await full.locator('#links').press('Enter');await full.keyboard.press('Enter');await full.getByText('9007199254740993123',{exact:true}).waitFor();await full.waitForFunction(()=>!document.querySelector('#copyAll').disabled);assert.equal(await full.evaluate(()=>testBatchIds.size),1);await full.close();group('Full account tools use Enter once for pasted content links, preserve Shift+Enter and prevent a parallel duplicate run.');
 await lookupPage.close();await lookupApi.close();group('Five native content-URL lookups resolve only bound fictional authors, retain exact string IDs and output canonical profile links.');
 const source=await context.newPage();await source.goto('https://www.instagram.com/alex.example/');
 const tabId=await api.evaluate(async()=> (await chrome.tabs.query({})).find(t=>t.url==='https://www.instagram.com/alex.example/').id);
 async function saveImage(url,{delay=false}={}){
  const opened=context.waitForEvent('page');await api.evaluate(async({url,tabId})=>{const tab=await chrome.tabs.get(tabId);return (await import('./source-image-launch.js')).launchSourceImage({srcUrl:url,pageUrl:tab.url},tab);},{url,tabId});
  const page=await opened;await page.waitForURL('**/source-image.html?*');
  if(delay){await page.waitForTimeout(100);while(!releaseDelayed)await page.waitForTimeout(20);await api.evaluate(scanId=>chrome.runtime.sendMessage({type:'workspace.action',action:{type:'context.select',scanId}}),ids.otherScan);releaseDelayed();releaseDelayed=null;}
  await page.locator('#sourceActions').waitFor({state:'visible'});const id=new URL(page.url()).searchParams.get('job');
  const record=await api.evaluate(async id=>(await import('./capture-store.js')).getCapture(id),id);assert.equal(record.savedState,'saved');return {page,record};
 }
 if(headed){
  await source.bringToFront();await source.locator('#image').click({button:'right'});await source.waitForTimeout(200);
  execFileSync(process.env.GATHER_XDOTOOL,['key','--clearmodifiers','End','Up','Up','Up','Return']);
  await api.waitForFunction(async()=>{const s=await import('./capture-store.js');return (await s.listCaptures()).some(r=>r.mode==='source-image'&&r.savedState==='saved');});
  await api.evaluate(async()=>{for(const tab of await chrome.tabs.query({}))if(tab.url?.includes('/source-image.html?'))await chrome.tabs.remove(tab.id);});
  group('Physical Edge context-menu invocation saves the clicked image and grants normal activeTab access.');
  for(const mode of ['visible','selection','full-page']){
   await source.bringToFront();const opened=context.waitForEvent('page');const launch=await api.evaluate(({mode,tabId,ids})=>chrome.runtime.sendMessage({type:'capture.start',mode,tabId,afterCapture:'none',destination:{scanId:ids.scan,projectId:ids.project},subjectId:ids.subject}),{mode,tabId,ids});assert.ok(!launch.error,launch.error);const controller=await opened;await controller.waitForURL('**/capture.html?*');
   if(mode==='selection'){await source.locator('#gather-selection-overlay').waitFor();await source.bringToFront();await source.mouse.move(40,140);await source.mouse.down();await source.mouse.move(750,740);await source.mouse.wheel(0,650);await source.waitForFunction(()=>scrollY>500);await source.mouse.move(750,760);await source.mouse.up();}
   await controller.waitForFunction(()=>!document.querySelector('#completed').hidden||document.querySelector('#status').classList.contains('error'),null,{timeout:35000});assert.ok(await controller.locator('#completed').isVisible(),await controller.locator('#status').innerText());
   const record=await api.evaluate(async id=>(await import('./capture-store.js')).getCapture(id),launch.launchId);assert.equal(record.scanId,ids.scan);assert.equal(record.subjectId,ids.subject);assert.equal(record.status,'complete');if(mode==='selection'){assert.equal(record.dimensions.width,710);assert.ok(record.dimensions.height>1100);}assert.equal(await source.evaluate(()=>scrollY),0);await controller.close();
  }
  group('One native analyst journey captures visible, scrolling selection and full page into the same Case/SOC with restored page position.');
  const zoomEvidence=[];
  for(const zoom of [0.8,1,1.25,1.5,2]){
   await source.bringToFront();await api.evaluate(({tabId,zoom})=>chrome.tabs.setZoom(tabId,zoom),{tabId,zoom});await source.waitForTimeout(100);
   const ratio=await source.evaluate(()=>devicePixelRatio),opened=context.waitForEvent('page');const launch=await api.evaluate(({tabId,ids})=>chrome.runtime.sendMessage({type:'capture.start',mode:'selection',tabId,afterCapture:'none',destination:{scanId:ids.scan,projectId:ids.project},subjectId:ids.subject}),{tabId,ids});assert.ok(!launch.error,launch.error);const controller=await opened;await controller.waitForURL('**/capture.html?*');await source.locator('#gather-selection-overlay').waitFor();await source.bringToFront();await source.mouse.move(20,220);await source.mouse.down();await source.mouse.move(120,300);await source.mouse.up();await controller.waitForFunction(()=>!document.querySelector('#completed').hidden||document.querySelector('#status').classList.contains('error'));assert.ok(await controller.locator('#completed').isVisible(),await controller.locator('#status').innerText());
   const geometry=await api.evaluate(async id=>{const s=await import('./capture-store.js'),r=await s.getCapture(id),original=await s.getAsset(r.assets.find(a=>a.role==='original').id,{verify:true}),selected=await s.getAsset(r.assets.find(a=>a.role==='derivative').id,{verify:true}),a=await createImageBitmap(original.blob),b=await createImageBitmap(selected.blob),v=r.technical.selectionViewport,sx=a.width/v.width,sy=a.height/v.height;const rect={x:Math.floor(20*sx+1e-7),y:Math.floor(220*sy+1e-7),width:Math.ceil(120*sx-1e-7)-Math.floor(20*sx+1e-7),height:Math.ceil(300*sy-1e-7)-Math.floor(220*sy+1e-7)};const canvas=document.createElement('canvas');canvas.width=rect.width;canvas.height=rect.height;const c=canvas.getContext('2d');c.drawImage(a,rect.x,rect.y,rect.width,rect.height,0,0,rect.width,rect.height);const expected=c.getImageData(0,0,rect.width,rect.height).data;c.clearRect(0,0,rect.width,rect.height);c.drawImage(b,0,0);const actual=c.getImageData(0,0,rect.width,rect.height).data;const equal=actual.every((value,index)=>value===expected[index]);a.close();b.close();return {dimensions:r.dimensions,expected:{width:rect.width,height:rect.height},css:r.technical.cssSelection,equal,scaleX:sx,scaleY:sy};},launch.launchId);assert.deepEqual(geometry.dimensions,geometry.expected);assert.deepEqual(geometry.css,{x:20,y:220,width:100,height:80});assert.equal(geometry.equal,true);zoomEvidence.push({zoom,ratio,...geometry});await controller.close();
  }
  await api.evaluate(tabId=>chrome.tabs.setZoom(tabId,1),tabId);await fs.writeFile(path.join(out,'native-zoom.json'),JSON.stringify(zoomEvidence,null,2));group('Native Edge zoom 80/100/125/150/200% retains exact selected-image dimensions; Windows display scaling remains separate.');

 }
 const captured=[];
 for(const ext of ['png','jpg','webp','avif','gif']){
  const url='https://www.instagram.com/fixture.'+ext,{page,record}=await saveImage(url);captured.push(record);
  const expected=images.get('/fixture.'+ext);assert.equal(record.assets[0].sha256,crypto.createHash('sha256').update(expected.bytes).digest('hex'));assert.equal(record.assets[0].mime,expected.type);assert.deepEqual(record.dimensions,{width:160,height:100});assert.equal(record.mode,'source-image');assert.equal(record.subjectId,ids.subject);assert.equal(record.technical.imageUrl,url);await page.close();
 }
 group('Native source-image acquisition preserves exact original bytes, MIME, dimensions and provenance for PNG/JPEG/WebP/AVIF/GIF.');
 const duplicate=await saveImage('https://www.instagram.com/fixture.png');assert.notEqual(duplicate.record.id,captured[0].id);await duplicate.page.close();
 const large=await saveImage('https://www.instagram.com/large.png');assert.deepEqual(large.record.dimensions,{width:4096,height:2048});await large.page.close();group('Deliberate duplicate saves get distinct records; an 8-megapixel source remains full size.');
 const cross=await saveImage('https://cdn.example.test/fixture.webp');assert.equal(cross.record.assets[0].sha256,crypto.createHash('sha256').update(images.get('/fixture.webp').bytes).digest('hex'));await cross.page.close();group('Cross-origin CDN fixture succeeds through CORS without new host permissions.');
 const delayed=await saveImage('https://www.instagram.com/delay.png',{delay:true});assert.equal(delayed.record.scanId,ids.scan);assert.equal(delayed.record.subjectId,ids.subject);await delayed.page.close();group('Changing the global case during delayed acquisition leaves the original Case/SOC frozen.');
 for(const url of ['https://www.instagram.com/denied.png','https://blocked.example.test/fixture.png','blob:https://example.test/temporary']){
  const opened=context.waitForEvent('page');await api.evaluate(async({url,tabId})=>(await import('./source-image-launch.js')).launchSourceImage({srcUrl:url,pageUrl:'https://www.instagram.com/alex.example/'},await chrome.tabs.get(tabId)),{url,tabId});const page=await opened;await page.waitForURL('**/source-image.html?*');await page.locator('#sourceStatus.error').waitFor().catch(async error=>{throw new Error(url+' → '+await page.locator('main').innerText()+'; '+error.message);});assert.equal(await page.locator('#sourceActions').isVisible(),false);await page.close();
 }
 group('Denied/CORS-blocked/blob sources fail visibly with no fake saved image or screenshot substitute.');
 await api.reload();await api.locator('.layout:not([inert])').waitFor();await api.getByRole('tab',{name:'Captures',exact:true}).click();await api.getByLabel('Browse captures',{exact:true}).selectOption('all');await api.locator('.capture-card').first().waitFor();assert.ok(await api.getByText('Source image',{exact:true}).count()>0);await api.locator('.capture-open').first().click();await api.locator('.capture-inspector').waitFor();assert.ok(await api.getByText('Reverse image search',{exact:true}).isVisible());await api.screenshot({path:path.join(out,'source-inspector.png')});
 const reverseOpened=context.waitForEvent('page');await api.getByRole('button',{name:'Reverse image search',exact:true}).click();const reverse=await reverseOpened;await reverse.waitForURL('**/image-search.html?*');await reverse.getByText('Selected locally. Nothing uploaded.',{exact:true}).waitFor();await reverse.getByLabel('Reverse image provider').selectOption('tineye');const providerOpened=context.waitForEvent('page');await reverse.getByRole('button',{name:'Copy & open search ↗',exact:true}).click();const provider=await providerOpened;await provider.waitForURL('https://tineye.com/');assert.ok(!provider.url().includes('image'));await provider.close();await reverse.bringToFront();await reverse.screenshot({path:path.join(out,'reverse-image.png')});await reverse.getByRole('button',{name:'Remove',exact:true}).click();assert.ok(await reverse.getByRole('button',{name:'Copy & open search ↗',exact:true}).isDisabled());await reverse.locator('input[type=file]').setInputFiles(path.join(temporary,'fixture.webp'));await reverse.getByText('Selected locally. Nothing uploaded.',{exact:true}).waitFor();const localProviderOpened=context.waitForEvent('page');await reverse.getByRole('button',{name:'Copy & open search ↗',exact:true}).click();const localProvider=await localProviderOpened;await localProvider.waitForURL('https://tineye.com/');await localProvider.close();await reverse.close();await api.locator('.capture-inspector').getByRole('button',{name:'Close',exact:true}).click();group('Reverse search selects a saved asset or local file, copies its pixels and explicitly opens the shared provider with no automatic upload.');
 const edit=await context.newPage();await edit.goto(base+'/capture-edit.html?id='+captured[0].id);await edit.locator('#saveDerivative').waitFor();await edit.getByRole('button',{name:'Black redaction',exact:true}).click();const box=await edit.locator('#editCanvas').boundingBox();await edit.mouse.move(box.x+10,box.y+10);await edit.mouse.down();await edit.mouse.move(box.x+45,box.y+45);await edit.mouse.up();await edit.locator('#saveAndCopy').click();await edit.getByText('Copied the selected image.',{exact:true}).waitFor();const revised=await api.evaluate(async id=>{const s=await import('./capture-store.js'),r=await s.getCapture(id);return {original:(await s.getAsset(r.assets.find(a=>a.role==='original').id,{verify:true})).sha256,share:(await s.getAsset(r.shareAssetId,{verify:true})).sha256};},captured[0].id);assert.equal(revised.original,captured[0].assets[0].sha256);assert.notEqual(revised.share,revised.original);await edit.close();group('Source-image manual redaction and Save & Copy use a derivative while the original byte hash stays unchanged.');
 await api.evaluate(async()=>{await(await import('./capture-store.js')).updateCaptureSettings({automaticSourceCopy:true,automaticCopy:false});});const auto=await saveImage('https://www.instagram.com/fixture.jpg');await auto.page.getByText('Image copied to clipboard.',{exact:true}).waitFor();await auto.page.close();const prefs=await api.evaluate(async()=>{const s=await import('./capture-store.js'),p=await s.getCaptureSettings();await s.updateCaptureSettings({automaticSourceCopy:false});return p;});assert.equal(prefs.automaticCopy,false);assert.equal(prefs.automaticSourceCopy,true);group('Source-image auto-copy works independently of screenshot auto-copy, converting only the clipboard copy to PNG.');
 await api.getByRole('tab',{name:'Research',exact:true}).click();const query=api.locator('#query');await query.fill('');await query.pressSequentially('si');await api.locator('.search-ghost:not([hidden])').waitFor();await query.press('Tab');assert.equal(await query.inputValue(),'site:');await query.pressSequentially('inst');await query.press('Enter');assert.equal(await query.inputValue(),'site:instagram.com');await query.pressSequentially(' "Fictional Example"');const searchOpened=context.waitForEvent('page');await query.press('Enter');const searchPage=await searchOpened;await searchPage.waitForURL('**google.com/search?*');assert.equal(new URL(searchPage.url()).searchParams.get('q'),'site:instagram.com "Fictional Example"');await searchPage.close();await api.waitForFunction(()=>document.querySelector('#query').value==='');
 const state=await api.evaluate(async()=>JSON.stringify({local:await chrome.storage.local.get(null),session:await chrome.storage.session.get(null)}));assert.ok(!state.includes('Fictional Example'));group('Native keyboard si → Tab → site: → inst → Enter → instagram.com → Enter launches exactly the requested query with no retained query.');
 await query.fill('si');await query.press('Escape');assert.equal(await api.locator('.search-ghost').isVisible(),false);await query.press('Tab');assert.notEqual(await api.evaluate(()=>document.activeElement.id),'query');await api.locator('#provider').selectOption('youtube');await query.fill('si');assert.equal(await api.locator('.search-ghost').isVisible(),false);await query.fill('');group('Escape dismisses completion, Tab releases focus, and unsupported provider operators are not suggested.');
 await api.getByRole('tab',{name:'Reference',exact:true}).click();assert.equal(await api.evaluate(()=>document.activeElement.id),'referenceSearch');await api.getByText('Manage local library',{exact:true}).click();
 const corpus=path.join(temporary,'Client Communication');await fs.mkdir(path.join(corpus,'Follow-up'),{recursive:true});await fs.mkdir(path.join(corpus,'Login-Info'),{recursive:true});await fs.writeFile(path.join(corpus,'Follow-up','No Findings.md'),'# No Findings\n\n## Requesting peers\nPlease provide peer names or usernames.\n');await fs.writeFile(path.join(corpus,'Login-Info','Private.md'),'# Login\npassword: fictional');
 await api.bringToFront();await api.locator('input[webkitdirectory]').setInputFiles(corpus).catch(async error=>{throw new Error(error.message+'\n'+await api.locator('#referenceLibrary').innerText());});await api.getByText(/Imported 1 files/).waitFor();await api.locator('#referenceSearch').fill('no accounts');await api.locator('#referenceSearch').press('Enter');assert.equal(await api.locator('.reference-preview pre').innerText(),'## Requesting peers\nPlease provide peer names or usernames.\n');await api.getByRole('button',{name:'Copy exact text',exact:true}).click();await api.getByText('Source wording copied. Review before using it.',{exact:true}).waitFor();group('Native local folder import excludes Login-Info, preserves hierarchy, ranks aliases and copies exact section wording.');
 await api.screenshot({path:path.join(out,'reference-desktop.png')});await api.setViewportSize({width:400,height:850});assert.ok(await api.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await api.screenshot({path:path.join(out,'reference-narrow.png')});await api.setViewportSize({width:1280,height:900});group('Reference and five-tab workspace remain usable at desktop and 400px without horizontal page overflow.');
 const panel=await context.newPage();await panel.goto(base+'/workspace.html?panel=1');await panel.locator('.layout:not([inert])').waitFor();await panel.setViewportSize({width:400,height:850});assert.ok(await panel.locator('a.panel-reference-link').isVisible());assert.ok(await panel.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.screenshot({path:path.join(out,'side-panel.png')});await panel.close();group('Compact side-panel content fits 400px and exposes the local Reference link.');
 const profileB=await open('profile-b');const clean=await profileB.page.evaluate(async()=>({local:await chrome.storage.local.get(null),captures:await(await import('./capture-store.js')).listCaptures(),refs:await(await import('./reference-store.js')).readReferenceLibrary()}));assert.ok(!JSON.stringify(clean).includes('PRIVATE_'));assert.equal(clean.captures.length,0);assert.equal(clean.refs.packs.length,0);assert.ok(!JSON.stringify(clean.local).includes('9007199254740993123'));group('A second native Edge profile using the identical extension has no Profile A cases, SOCs, images or Reference data.');
 await context.setOffline(true);await api.reload();await api.locator('.layout:not([inert])').waitFor();await api.getByRole('tab',{name:'Reference',exact:true}).click();await api.locator('#referenceSearch').fill('no accounts');assert.ok(await api.locator('.reference-title').count());const offline=await api.evaluate(async id=>{const store=await import('./capture-store.js'),capture=await store.getCapture(id),asset=await store.getAsset(capture.assets[0].id,{verify:true});const backup=await chrome.runtime.sendMessage({type:'workspace.backup'});return {sha:asset.sha256,backup:backup.error||'available'};},captured[0].id);assert.equal(offline.sha,captured[0].assets[0].sha256);group('Offline reload preserves local cases, source-image bytes and Reference search without a work-data backend.');await context.setOffline(false);
 const restored=await api.evaluate(async()=>{const {createFullBackup,readFullBackup,stageFullRestore}=await import('./capture-backup.js');const reply=await chrome.runtime.sendMessage({type:'workspace.backup'});if(reply.error)throw Error(reply.error);const blob=await createFullBackup(reply.backup),manifest=await readFullBackup(blob);const imported=await chrome.runtime.sendMessage({type:'workspace.importImages',stageId:await stageFullRestore(manifest)});if(imported.error)throw Error(imported.error);const store=await import('./capture-store.js'),copies=await store.listCaptures();for(const original of manifest.bundle.captures.filter(c=>c.savedState==='saved')){const copy=copies.find(c=>c.projectId===imported.result.idMap[original.projectId]&&c.startedAt===original.startedAt);if(!copy||copy.scanId!==imported.result.idMap[original.scanId]||copy.subjectId!==(original.subjectId?imported.result.idMap[original.subjectId]:null))throw Error('Restore relationship mismatch');const blob=await store.getAsset(copy.assetIds[0],{verify:true});if(blob.sha256!==original.assets[0].sha256)throw Error('Restored bytes differ');}return {count:manifest.bundle.captures.filter(c=>c.mode==='source-image'&&c.savedState==='saved').length,types:manifest.bundle.assets.map(a=>a.mime)};});assert.ok(restored.count>=8);assert.ok(restored.types.includes('image/avif'));group('Binary backup validates and merge-restores all source-image formats, original hashes and remapped Case/scan/SOC relationships.');
 const libraryRoundtrip=await api.evaluate(async()=>{const s=await import('./reference-store.js'),m=await import('./reference-model.js'),first=await s.readReferenceLibrary(),pack=first.packs[0];const exported=m.readReferencePack(JSON.stringify(pack));await s.saveReferencePack({...exported,version:'2'},first.revision);let rejected=false;try{await s.saveReferencePack(pack,first.revision);}catch{rejected=true;}const next=await s.readReferenceLibrary();await s.deleteReferencePack(pack.id,next.revision);const empty=await s.readReferenceLibrary();await s.saveReferencePack(exported,empty.revision);return {rejected,deleted:empty.packs.length===0,exact:(await s.readReferenceLibrary()).packs[0].files[0].text===pack.files[0].text};});assert.deepEqual(libraryRoundtrip,{rejected:true,deleted:true,exact:true});group('Reference JSON round-trip, replacement, stale-write protection and local deletion preserve exact source text.');
 const requestsText=JSON.stringify(requests);for(const sentinel of canaries)assert.ok(!requestsText.includes(sentinel),'Private canary escaped in network traffic');group('Private Case/SOC/note canaries never occur in captured outbound URL, headers or request bodies.');
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'results.json'),JSON.stringify({status:'passed',version:manifest.version,kind:'native-installed-Edge-fictional-network',passed,errors,requests:requests.length,limits:headed?'Physical Edge invocation and screenshots; fictional platform responses. No Windows OS dialogs or live platform claim.':'Scripted launch with real Edge APIs; no physical context-menu invocation, Windows OS dialogs or live platform claim.'},null,2));console.log('PASS '+passed.length+' R6 native groups');
}catch(error){await fs.writeFile(path.join(out,'results.json'),JSON.stringify({status:'failed',passed,errors,error:error.stack},null,2));throw error;}finally{releaseDelayed?.();for(const ctx of contexts.reverse())await ctx.close();await fs.rm(temporary,{recursive:true,force:true});}
