// Actual rendered product modules + native canvas/IndexedDB. Chrome extension APIs
// are controlled doubles: this is NOT native extension/activeTab acceptance.
import {createRequire} from 'node:module';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const {chromium}=createRequire(import.meta.url)('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../account-id-tool'),artifacts=process.env.GATHER_BROWSER_ARTIFACTS||path.resolve(root,'../../artifacts/browser-toolbar');await fs.mkdir(artifacts,{recursive:true});
const server=http.createServer(async(req,res)=>{try{if(req.url==='/fixture'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><style>html{scroll-behavior:smooth}body{margin:0;font:24px sans-serif;background:#eef4ef}header{position:sticky;top:0;background:#17684b;color:white;padding:20px}.block{height:750px;padding:20px}</style><header>Northbridge — fictional fixture</header><div class="block">Alex Example · October review</div><div class="block">Second section — deterministic data</div><div class="block">Third section — no real people</div>');return;}const name=decodeURIComponent(new URL(req.url,'http://test').pathname).slice(1)||'workspace.html';const full=path.resolve(root,name);if(!full.startsWith(root+path.sep))throw new Error('path');const data=await fs.readFile(full);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'})[path.extname(full)]||'application/octet-stream');res.end(data);}catch{res.writeHead(404);res.end('missing');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,profile=await fs.mkdtemp(path.join(os.tmpdir(),'gather-rendered-'));let context,source;
const events=[];
try{
  context=await chromium.launchPersistentContext(profile,{executablePath:process.env.GATHER_CHROMIUM_PATH||'/usr/lib/chromium/chromium',chromiumSandbox:true,headless:true,viewport:{width:1280,height:800}});
  await context.exposeBinding('__gatherInject',async(_,{fn,args})=>source.evaluate(({fn,args})=>{const f=(0,eval)('('+fn+')');return f(...args);},{fn,args}));
  await context.exposeBinding('__gatherScreenshot',async()=>{await source.bringToFront();return 'data:image/png;base64,'+(await source.screenshot()).toString('base64');});
  await context.addInitScript(({origin})=>{
    if(location.pathname==='/fixture')return;if(location.origin!=='null')origin=location.origin;
    const event=()=>{const listeners=new Set();return {addListener:f=>listeners.add(f),removeListener:f=>listeners.delete(f),emit:(...args)=>{for(const f of listeners)f(...args);}};};
    const changed=event(),area=prefix=>({async get(key){const all=JSON.parse(localStorage.getItem(prefix)||'{}');return key===null?all:{[key]:all[key]};},async set(values){const all=JSON.parse(localStorage.getItem(prefix)||'{}'),changes={};for(const [key,value]of Object.entries(values)){changes[key]={oldValue:all[key],newValue:value};all[key]=value;}localStorage.setItem(prefix,JSON.stringify(all));changed.emit(changes,prefix==='local'?'local':'session');},async remove(key){const all=JSON.parse(localStorage.getItem(prefix)||'{}');delete all[key];localStorage.setItem(prefix,JSON.stringify(all));},async setAccessLevel(){}});
    const readTabs=()=>JSON.parse(localStorage.getItem('mockTabs')||'[]'),writeTabs=rows=>localStorage.setItem('mockTabs',JSON.stringify(rows));
    const tabs={onCreated:event(),onRemoved:event(),onActivated:event(),onUpdated:event(),onReplaced:event(),async query(q){return readTabs().filter(t=>(!q?.active||t.active)&&(!q?.windowId||t.windowId===q.windowId));},async get(id){const t=readTabs().find(t=>t.id===id);if(!t)throw new Error('No tab');return t;},async getCurrent(){return location.pathname==='/workspace.html'&&!new URLSearchParams(location.search).has('panel')?{id:99}:undefined;},async create(options){const t={id:Math.floor(Math.random()*1e8),windowId:1,active:options.active!==false,...options};const rows=readTabs();if(t.active)rows.forEach(r=>r.active=false);rows.push(t);writeTabs(rows);tabs.onCreated.emit(t);return t;},async update(id,options){const rows=readTabs(),t=rows.find(t=>t.id===id);if(options.active)rows.forEach(r=>r.active=false);Object.assign(t,options);writeTabs(rows);tabs.onUpdated.emit(id,options,t);return t;},async remove(id){writeTabs(readTabs().filter(t=>t.id!==id));tabs.onRemoved.emit(id);},async captureVisibleTab(){return __gatherScreenshot();}};
    const windows={onRemoved:event(),async getCurrent(){return {id:location.pathname==='/capture.html'?2:1};},async get(id){if(id===2&&localStorage.getItem('captureOpen')!=='true')throw new Error('No window');return {id};},async update(){return {};},async create({url}){localStorage.setItem('captureOpen','true');window.open(url,'gather-test-capture');return {id:2};}};
    let downloadId=1;const downloads={onChanged:event(),async download(options){if(localStorage.getItem('denyDownloads')==='true')throw new Error('Folder access denied (test double)');const n=downloadId++;localStorage.setItem('lastDownload',JSON.stringify(options));return n;},async search({id}){return [{id,state:'complete'}];}};
    globalThis.chrome={runtime:{id:'gather-test',getURL:f=>origin+'/'+f,onMessage:event(),onInstalled:event(),onStartup:event(),async sendMessage(m){try{if(m.type==='capture.start')return await (await import(origin+'/capture-launch.js')).launchCapture(m);if(m.type==='capture.finished')return await (await import(origin+'/capture-launch.js')).finishCapture(m.launchId);if(m.type.startsWith('quick.'))return await (await import(origin+'/quick-worker.js')).handleQuick(m);return await (await import(origin+'/workspace-store.js')).handleWorkspace(m);}catch(e){return {error:e.message};}}},storage:{local:area('local'),session:area('session'),onChanged:changed},tabs,windows,downloads,scripting:{async executeScript({func,args=[]}){if(localStorage.getItem('denyScript')==='true')throw new Error('Page access denied (double)');if(func.toString().includes('outerHTML'))return [{result:JSON.parse(localStorage.getItem('lookupFixture')||'null')}];return [{result:await __gatherInject({fn:func.toString(),args}),documentId:'fixture-document'}];}},contextMenus:{update:async()=>{}},action:{setBadgeText:async()=>{}},sidePanel:{open:async()=>{}}};
    globalThis.__seedTabs=rows=>writeTabs(rows);const nativeFetch=globalThis.fetch;globalThis.fetch=(input,options)=>{const url=new URL(String(input),location.href);if(url.origin!==location.origin&&!['data:','blob:'].includes(url.protocol)){localStorage.setItem('externalFetches',String(Number(localStorage.getItem('externalFetches')||0)+1));throw new Error('Live network disabled in test');}return nativeFetch(input,options);};
    addEventListener('storage',event=>{if(['local','session'].includes(event.key)){const before=JSON.parse(event.oldValue||'{}'),after=JSON.parse(event.newValue||'{}'),diff={};for(const key of new Set([...Object.keys(before),...Object.keys(after)]))if(JSON.stringify(before[key])!==JSON.stringify(after[key]))diff[key]={oldValue:before[key],newValue:after[key]};changed.emit(diff,event.key);}});
  },{origin});
  source=await context.newPage();await source.goto(origin+'/fixture');const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/workspace.html');
  await page.evaluate(({origin})=>__seedTabs([{id:10,windowId:1,url:origin+'/fixture',title:'Northbridge fictional page',active:true}]),{origin});
  const ids=await page.evaluate(async()=>{
    const send=action=>chrome.runtime.sendMessage({type:'workspace.action',action});
    const a=await send({type:'project.create',name:'Northbridge',scanName:'SEO 6'}),scanA=a.result.scanId,projectA=a.result.id;
    const store=await import('./capture-store.js'),subject=await store.createSubject({projectId:projectA,name:'Alex Example'});await store.selectSubject(scanA,subject.id,projectA);
    const b=await send({type:'project.create',name:'Southridge',scanName:'SD 73'});await send({type:'context.select',scanId:scanA});
    return {scanA,projectA,subjectId:subject.id,scanB:b.result.scanId};
  });
  const fresh=async()=>{const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewportSize({width:420,height:600});await p.goto(origin+'/popup.html');await p.waitForFunction(()=>!document.querySelector('#captureScan').disabled);return p;};
  const popup=await fresh();assert.equal(await popup.locator('#captureScan').inputValue(),ids.scanA);assert.equal(await popup.locator('#toolbarSubject').inputValue(),ids.subjectId);assert.equal(await popup.locator('[data-capture-mode]:visible').count(),3);assert.equal(await popup.locator('#pageOptions').getAttribute('open'),null);assert.equal(await popup.evaluate(()=>document.activeElement.id),'quickLinks');
  await page.evaluate(scanId=>chrome.runtime.sendMessage({type:'workspace.action',action:{type:'context.select',scanId}}),ids.scanB);
  await popup.waitForFunction(()=>document.querySelector('#useDefaultScan').textContent.includes('SD 73'));assert.equal(await popup.locator('#captureScan').inputValue(),ids.scanA);
  await popup.screenshot({path:path.join(artifacts,'direct-toolbar.png'),fullPage:true});events.push('Three direct screenshot actions and one Save to selector are visible; focused lookup and optional subject retained; a default switch leaves the displayed SEO 6 destination unchanged.');
  const opened=context.waitForEvent('page');await popup.getByRole('button',{name:'Full page',exact:true}).click();const capture=await opened;capture.on('pageerror',e=>errors.push(e.message));await capture.waitForFunction(()=>!document.querySelector('#completed').hidden||document.querySelector('#status').classList.contains('error'));assert.equal(await capture.locator('#completed').isVisible(),true,await capture.locator('#status').innerText());await capture.waitForFunction(()=>document.querySelector('#resultImage').naturalWidth>0);
  const saved=await page.evaluate(async()=>(await(await import('./capture-store.js')).listCaptures())[0]);assert.equal(saved.scanId,ids.scanA);assert.equal(saved.subjectId,ids.subjectId);assert.equal(saved.status,'complete');assert.ok(saved.assets.filter(a=>a.role==='tile').length>=3);
  assert.ok(await capture.locator('.image-viewport').evaluate(e=>e.scrollHeight>e.clientHeight));await capture.getByRole('button',{name:'Fit image',exact:true}).click();assert.ok(await capture.locator('#resultImage').evaluate(e=>e.height<=innerHeight*.58+1));await capture.getByRole('button',{name:'Fit width',exact:true}).click();await capture.screenshot({path:path.join(artifacts,'full-page-saved.png'),fullPage:true});events.push('Full page launches directly from the popup into the real controller, stitches real fixture screenshots and saves SEO 6/Alex despite SD 73 being active; width/whole-image viewing works.');
  await capture.getByRole('button',{name:'View in scan',exact:true}).click();await capture.waitForFunction(()=>JSON.parse(localStorage.getItem('mockTabs')||'[]').some(t=>t.url?.includes('capture=')));const link=await capture.evaluate(async()=>(await chrome.tabs.query({})).find(t=>t.url?.includes('capture=')).url);assert.equal(new URL(link).searchParams.get('scan'),ids.scanA);assert.equal(new URL(link).searchParams.get('capture'),saved.id);
  const workspace=await context.newPage();workspace.on('pageerror',e=>errors.push(e.message));await workspace.goto(link);await workspace.getByRole('heading',{name:'SEO 6',exact:true}).waitFor();await workspace.getByRole('dialog').waitFor();await workspace.waitForFunction(()=>document.querySelector('.inspector-image')?.naturalWidth>0);assert.equal(await workspace.getByRole('tab',{name:'Captures',exact:true}).getAttribute('aria-selected'),'true');await workspace.screenshot({path:path.join(artifacts,'linked-inspector.png'),fullPage:true});await workspace.keyboard.press('Escape');await page.evaluate(()=>chrome.tabs.update(10,{active:true}));events.push('View in scan selects the captured scan and opens that exact image, even when another case was active during workspace initialization.');
  await capture.close();await page.evaluate(()=>localStorage.setItem('captureOpen','false'));if(!popup.isClosed())await popup.close();
  const select=await fresh();await select.locator('#captureScan').selectOption(ids.scanB);await select.waitForFunction(id=>document.querySelector('#captureScan').value===id&&!document.querySelector('#captureScan').disabled,ids.scanB);assert.equal(await page.evaluate(async()=>(await chrome.runtime.sendMessage({type:'workspace.state'})).state.activeScanId),ids.scanA);await select.locator('#pageOptions summary').click();await select.getByRole('button',{name:'Save page link',exact:true}).click();await select.getByText(/Page link saved to.*SD 73/).waitFor();const item=await page.evaluate(async()=>(await chrome.runtime.sendMessage({type:'workspace.state'})).state.items.at(-1));assert.equal(item.scanId,ids.scanB);assert.equal(item.kind,'source');
  await select.getByRole('button',{name:/Use workspace default/}).click();await select.waitForFunction(id=>document.querySelector('#captureScan').value===id&&!document.querySelector('#captureScan').disabled,ids.scanA);const tabContext=await page.evaluate(()=>chrome.runtime.sendMessage({type:'workspace.tabContext',tabId:10}));assert.equal(tabContext.context.source,'detached');await select.close();events.push('Changing Save to assigns this tab without moving the workspace default; Save page link files only metadata to SD 73; explicit default action detaches the assignment.');
  const visible=await fresh();const visibleOpened=context.waitForEvent('page');await visible.getByRole('button',{name:'Visible area',exact:true}).click();const visibleCapture=await visibleOpened;await visibleCapture.locator('#completed').waitFor({state:'visible'});const visibleRecord=await page.evaluate(async()=>(await(await import('./capture-store.js')).listCaptures()).find(c=>c.mode==='visible'));assert.equal(visibleRecord.scanId,ids.scanA);assert.deepEqual(visibleRecord.dimensions,{width:1280,height:800});await visibleCapture.close();await page.evaluate(()=>localStorage.setItem('captureOpen','false'));if(!visible.isClosed())await visible.close();events.push('Visible area is a single toolbar action; the saved original has the actual viewport dimensions.');
  const selection=await fresh();const selectionOpened=context.waitForEvent('page');await selection.getByRole('button',{name:'Select area',exact:true}).click();const selectionCapture=await selectionOpened;await selectionCapture.locator('#selection').waitFor({state:'visible'});await selectionCapture.locator('#preview').scrollIntoViewIfNeeded();await selectionCapture.waitForFunction(()=>document.querySelector('#preview').naturalWidth>0);const bounds=await selectionCapture.locator('#preview').boundingBox();await selectionCapture.mouse.move(bounds.x+20,bounds.y+25);await selectionCapture.mouse.down();await selectionCapture.mouse.move(bounds.x+200,bounds.y+150);await selectionCapture.mouse.up();assert.equal(await selectionCapture.locator('#selectionCoordinates').getAttribute('open'),null);await selectionCapture.getByRole('button',{name:'Save selection',exact:true}).click();await selectionCapture.locator('#completed').waitFor({state:'visible'});const selected=await page.evaluate(async()=>(await(await import('./capture-store.js')).listCaptures()).find(c=>c.mode==='selection'));assert.ok(selected.dimensions.width<1280&&selected.dimensions.width>100);assert.equal(selected.assets.filter(a=>a.role==='original').length,1);assert.equal(selected.assets.filter(a=>a.role==='derivative').length,1);await selectionCapture.close();await page.evaluate(()=>localStorage.setItem('captureOpen','false'));if(!selection.isClosed())await selection.close();events.push('Select area supports an actual pointer drag without coordinate dialogs and retains the original plus cropped derivative.');
  await page.evaluate(()=>localStorage.setItem('denyScript','true'));const denied=await fresh();await denied.getByRole('button',{name:'Visible area',exact:true}).click();await denied.locator('#pageToolsStatus').getByText(/toolbar button/).waitFor();assert.equal(await denied.evaluate(async()=>(await(await import('./capture-store.js')).listCaptures()).length),3);await denied.evaluate(()=>localStorage.setItem('denyScript','false'));await denied.close();events.push('Denied scripting access produces actionable toolbar guidance and creates no image or controller.');
  await page.evaluate(()=>__seedTabs([{id:10,windowId:1,url:'chrome://extensions/',active:true,status:'complete'}]));const restricted=await fresh();for(const id of ['captureFullPage','captureVisible','captureSelection'])assert.equal(await restricted.locator('#'+id).isDisabled(),true);assert.equal(await restricted.locator('#quickLinks').isDisabled(),false);await restricted.close();events.push('Restricted pages disable screenshots while project-free pasted lookup remains available.');
  const fictionalUrl='https://www.instagram.com/alex.example/';await page.evaluate(({fictionalUrl})=>{__seedTabs([{id:10,windowId:1,url:fictionalUrl,title:'Fictional profile',active:true,status:'complete'}]);localStorage.setItem('lookupFixture',JSON.stringify({url:fictionalUrl,html:'<script type="application/json">{"username":"alex.example","id":"9007199254740993123","full_name":"Alex Example"}</script>'}));},{fictionalUrl});const quick=await fresh();await context.grantPermissions(['clipboard-read','clipboard-write'],{origin});await quick.getByRole('button',{name:'Run on this page',exact:true}).click();await quick.getByText('9007199254740993123',{exact:true}).waitFor();await quick.getByRole('button',{name:'Copy IDs',exact:true}).click();assert.equal(await quick.evaluate(()=>navigator.clipboard.readText()),'9007199254740993123');assert.equal(await quick.evaluate(async()=>(await chrome.runtime.sendMessage({type:'quick.state'})).submittedInput),fictionalUrl);assert.equal(await quick.evaluate(()=>localStorage.getItem('externalFetches')),null);events.push('Actual Run on this page and Copy IDs preserve the exact long fictional ID, with no fetched substitute or live network.');
  await quick.evaluate(url=>localStorage.setItem('lookupFixture',JSON.stringify({url,html:'<script>const captchaLibrary="checkpoint";</script><p>Profile data is still loading</p>'})),fictionalUrl);await quick.getByRole('button',{name:'Run on this page',exact:true}).click();await quick.locator('.account-row .row-issue').getByText(/No matching account ID/).waitFor();assert.doesNotMatch(await quick.locator('.account-row .row-issue').innerText(),/sign in|security check/i);await quick.getByRole('button',{name:'Retry unfinished',exact:true}).waitFor({state:'visible'});const failedInput=await quick.evaluate(async()=>(await chrome.runtime.sendMessage({type:'quick.state'})).input);assert.equal(await quick.locator('#quickLinks').inputValue(),fictionalUrl,'Failed input must remain (worker input: '+failedInput+')');const failedBatch=await quick.evaluate(async()=>(await chrome.runtime.sendMessage({type:'quick.state'})).batch);
  await page.evaluate(scanId=>chrome.runtime.sendMessage({type:'workspace.action',action:{type:'context.select',scanId}}),ids.scanB);await quick.evaluate(url=>localStorage.setItem('lookupFixture',JSON.stringify({url,html:'<script type="application/json">{"username":"alex.example","id":"9007199254740993123"}</script>'})),fictionalUrl);await quick.getByRole('button',{name:'Retry unfinished',exact:true}).click();await quick.getByText('9007199254740993123',{exact:true}).waitFor();await quick.waitForFunction(()=>!document.querySelector('#copyQuick').disabled);const retried=await quick.evaluate(async()=>(await chrome.runtime.sendMessage({type:'quick.state'})).batch);assert.equal(retried.id,failedBatch.id);assert.deepEqual(retried.lookupContext,failedBatch.lookupContext);assert.equal(retried.entries[0].key,failedBatch.entries[0].key);assert.equal(await quick.evaluate(async()=>(await chrome.runtime.sendMessage({type:'quick.state'})).submittedInput),fictionalUrl);assert.equal(await quick.evaluate(()=>localStorage.getItem('externalFetches')),null);events.push('Missing hydrated data stays technical; Retry recovers the same row/batch and scan after a default switch, without false sign-in advice or network.');
  await quick.evaluate(url=>localStorage.setItem('lookupFixture',JSON.stringify({url,html:'<p>Log in to Instagram</p>'})),fictionalUrl);await quick.getByRole('button',{name:'Run on this page',exact:true}).click();await quick.locator('.account-row .row-issue').getByText(/page asks you to sign in/i).waitFor();await quick.waitForFunction(()=>!document.querySelector('#retryQuick').disabled);assert.ok((await quick.locator('#quickList').boundingBox()).height>=120);await quick.locator('#quickList').scrollIntoViewIfNeeded();assert.ok(await quick.locator('#quickList').evaluate(e=>{const b=e.getBoundingClientRect();return b.top>=54&&b.bottom<=innerHeight;}));await quick.screenshot({path:path.join(artifacts,'observed-login.png'),fullPage:true});events.push('Observed sign-in text produces specific advice; missing markup never claims Gone or identity.');
  assert.deepEqual(errors,[]);console.log('PASS rendered toolbar journey with Chrome API doubles\n'+events.map((e,i)=>`${i+1}. ${e}`).join('\n'));await fs.writeFile(path.join(artifacts,'results.json'),JSON.stringify({kind:'rendered-browser-with-extension-api-doubles',nativeExtension:false,passed:events,errors},null,2));
}finally{await context?.close();server.close();await fs.rm(profile,{recursive:true,force:true});}
