import test from 'node:test';import assert from 'node:assert/strict';
import {emptyState,reduceWorkspace,WORKSPACE_KEY} from '../account-id-tool/workspace-model.js';
let local={},session={},created=[],access=true,active=true;
const area=ref=>({async get(key){return key===null?structuredClone(ref()):{[key]:structuredClone(ref()[key])};},async set(values){Object.assign(ref(),structuredClone(values));},async remove(key){delete ref()[key];}});
globalThis.chrome={runtime:{getURL:f=>'chrome-extension://gather/'+f},storage:{local:area(()=>local),session:area(()=>session)},tabs:{async get(id){return {id,windowId:1,url:'https://example.test/fixture',title:'Alex Example',active};},async query(){return [await this.get(10)];}},scripting:{async executeScript(){if(!access)throw new Error('Access denied');return [{result:true}];}},windows:{async get(id){if(!created.some(w=>w.id===id))throw new Error('Closed');return {id};},async create(options){const window={id:created.length+2,...options};created.push(window);return window;}}};
const {launchCapture,finishCapture}=await import('../account-id-tool/capture-launch.js');
function fixture(){local={};session={};created=[];access=true;active=true;let s=emptyState();const run=action=>{const r=reduceWorkspace(s,action);s=r.state;return r.result;};const a=run({type:'project.create',name:'Northbridge',scanName:'October review'}),search=run({type:'search.prepare',scanId:a.scanId,query:'Alex Example',provider:'google'}),b=run({type:'project.create',name:'Southridge',scanName:'Intake'});local[WORKSPACE_KEY]=s;return {a,b,destination:{scanId:a.scanId,projectId:a.id,originatingSearchId:search.id}};}
test('capture start freezes the displayed destination even if default and tab assignment change before worker work',async()=>{const f=fixture();session['gather.tabContexts.v1']={10:{scanId:f.b.scanId,projectId:f.b.id,originatingSearchId:null,source:'assigned'}};const r=await launchCapture({mode:'visible',tabId:10,subjectId:null,destination:f.destination});const seed=session['gather.captureLaunch.'+r.launchId];assert.equal(seed.context.scanId,f.a.scanId);assert.equal(seed.refs.searchId,f.destination.originatingSearchId);assert.equal(created[0].focused,false);assert.equal(seed.source.tabId,10);});
test('capture start rejects stale cross-project displayed context before creating a window',async()=>{const f=fixture();await assert.rejects(launchCapture({mode:'selection',tabId:10,subjectId:null,destination:{...f.destination,projectId:f.b.id}}),/unavailable/);assert.equal(created.length,0);});
test('side-panel capture without page invocation fails with activeTab guidance and no launch',async()=>{const f=fixture();access=false;await assert.rejects(launchCapture({mode:'visible',tabId:10,subjectId:null,destination:f.destination}),/toolbar/);assert.equal(created.length,0);assert.ok(!Object.keys(session).some(k=>k.startsWith('gather.captureLaunch.')));});
test('capture cannot target an inactive tab',async()=>{const f=fixture();active=false;await assert.rejects(launchCapture({mode:'visible',tabId:10,subjectId:null,destination:f.destination}),/toolbar/);assert.equal(created.length,0);});
test('capture lock survives worker-style session state and prevents overlapping controllers',async()=>{const f=fixture(),m={mode:'visible',tabId:10,subjectId:null,destination:f.destination};const first=await launchCapture(m);await assert.rejects(launchCapture(m),/Finish or cancel/);await finishCapture('wrong-id');await assert.rejects(launchCapture(m),/Finish or cancel/);await finishCapture(first.launchId);const second=await launchCapture(m);assert.notEqual(first.launchId,second.launchId);});

test('navigation after toolbar opens rejects the displayed URL before launching or reading the page',async()=>{const f=fixture();await assert.rejects(launchCapture({mode:'visible',tabId:10,destination:f.destination,expectedUrl:'https://example.test/previous'}),/page changed/);assert.equal(created.length,0);assert.ok(!Object.keys(session).some(k=>k.startsWith('gather.captureLaunch.')));});
test('selection-and-copy is frozen into the controller seed and unsupported actions do not launch',async()=>{const f=fixture();await assert.rejects(launchCapture({mode:'selection',afterCapture:'send',destination:f.destination}),/supported/);await assert.rejects(launchCapture({mode:'selection',selectionMethod:'unknown',destination:f.destination}),/supported/);assert.equal(created.length,0);const r=await launchCapture({mode:'selection',afterCapture:'copy',subjectId:null,destination:f.destination});assert.equal(session['gather.captureLaunch.'+r.launchId].afterCapture,'copy');assert.equal(session['gather.captureLaunch.'+r.launchId].selectionMethod,'page');});
