import test from 'node:test';import assert from 'node:assert/strict';
import {selectionBounds,fullPagePlan,acquireCapture,CaptureStopped} from '../account-id-tool/capture-engine.js';
import {safePathName,captureExportPath,preferredCaptureAsset,captureExportRecord} from '../account-id-tool/capture-files.js';
import {frozenDestination,hashBytes} from '../account-id-tool/capture-store.js';
function adapter({totalHeight=2400,height=800,onShot=()=>{},onSleep=()=>{},failAt=Infinity}={}){
  let now=1000,y=55,shots=0,restored=false,disposed=false;const times=[],operations=[];
  const metrics=()=>({url:'https://example.test',width:1000,height,devicePixelRatio:2,visualScale:1,scrollX:0,scrollY:y,totalHeight,totalWidth:1000,stickyElements:1,nestedScrollers:0});
  return {times,operations,get restored(){return restored;},get disposed(){return disposed;},now:()=>now,async sleep(ms){now+=ms;onSleep();},async assertSource(){},async page(op,token,args){operations.push(op);if(op==='scroll')y=args.y;if(op==='restore'){restored=true;y=55;}return metrics();},async screenshot(){shots++;onShot(shots);if(shots===failAt)throw new CaptureStopped('Source tab changed');times.push(now);return new Blob(['synthetic '+shots],{type:'image/png'});},async dimensions(){return {width:2000,height:height*2};},async compose(tiles,plan){return new Blob(['stitched '+tiles.length+' '+plan.height],{type:'image/png'});},dispose(){disposed=true;}};
}
test('rectangle bounds clamp negative drag, preserve pixel coordinates, reject empty or nonfinite',()=>{assert.deepEqual(selectionBounds({x:20,y:20,width:-30,height:40},100,100),{x:0,y:20,width:20,height:40});assert.throws(()=>selectionBounds({x:0,y:0,width:NaN,height:4},10,10));assert.throws(()=>selectionBounds({x:0,y:0,width:0,height:4},10,10));});
test('full-page plan bounds high DPI pixels and bottom overlap',()=>{const p=fullPagePlan({width:1000,height:800,totalHeight:2100,devicePixelRatio:2});assert.deepEqual(p.positions,[0,800,1300]);assert.equal(p.height,4200);const bounded=fullPagePlan({width:1000,height:800,totalHeight:900000,devicePixelRatio:2});assert.ok(bounded.bounded);assert.ok(bounded.width*bounded.height<=48000000);assert.ok(bounded.positions.length<=24);});
test('visible capture keeps original bytes, dimensions, scale and scroll',async()=>{const a=adapter(),r=await acquireCapture({adapter:a,mode:'visible'});assert.equal(r.assets.length,1);assert.equal(r.assets[0].role,'original');assert.equal(r.scale,2);assert.equal(r.coordinates.scrollY,55);assert.ok(a.disposed);});
test('full-page pacing preserves tiles, restores page and marks stitch as derivative',async()=>{const a=adapter(),r=await acquireCapture({adapter:a,mode:'full-page'});assert.equal(r.status,'complete');assert.equal(r.assets.filter(a=>a.role==='tile').length,3);assert.equal(r.assets[0].role,'derivative');assert.ok(a.times.slice(1).every((t,i)=>t-a.times[i]>=650));assert.ok(a.restored);assert.ok(a.disposed);});
test('cancel while scrolling restores source and does not claim a completed capture',async()=>{const controller=new AbortController(),a=adapter({onSleep:()=>controller.abort()});await assert.rejects(acquireCapture({adapter:a,mode:'full-page',signal:controller.signal}),CaptureStopped);assert.ok(a.restored);assert.ok(a.disposed);});
test('tab change after a validated tile retains only validated pixels and marks partial',async()=>{const a=adapter({failAt:2}),r=await acquireCapture({adapter:a,mode:'full-page'});assert.equal(r.status,'partial');assert.equal(r.assets.filter(a=>a.role==='tile').length,1);assert.ok(r.limitations.some(x=>/Source tab changed/.test(x)));assert.ok(a.restored);});
test('bounded page can never be labeled complete',async()=>{const a=adapter({totalHeight:10000}),r=await acquireCapture({adapter:a,mode:'full-page',limits:{maxTiles:2}});assert.equal(r.status,'partial');assert.equal(r.assets.filter(x=>x.role==='tile').length,2);});
test('frozen destination rejects mixed Inbox/project and is immutable',()=>{assert.throws(()=>frozenDestination({projectId:'p',scanId:null}));const d=frozenDestination({projectId:'p',scanId:'s',subjectId:'alex',projectName:'Northbridge'});assert.ok(Object.isFrozen(d));assert.equal(d.projectName,'Northbridge');});
test('paths avoid reserved names, traversal, separators and same-name subject collisions',()=>{assert.equal(safePathName('CON'),'_CON');assert.ok(!/[\\/:]/.test(safePathName('../Alex:Example\\file')));const r={id:'capture-a',startedAt:1780000000000,source:{url:'https://example.test/'},mode:'selection',context:{projectId:'project-a',projectName:'Northbridge',scanId:'scan-a',scanName:'October review',subjectId:'subject-a',subjectName:'Alex Example'}};const a=captureExportPath(r),b=captureExportPath({...r,context:{...r.context,subjectId:'subject-b'}});assert.notEqual(a,b);assert.ok(a.startsWith('Gather/'));assert.ok(a.length<240);});
test('shareable rectangle chooses derivative and does not include original pixels',()=>{const r={id:'a',assets:[{id:'original',role:'original'},{id:'crop',role:'derivative'}],source:{},context:{},refs:{}};const a=preferredCaptureAsset(r);assert.equal(a.id,'crop');assert.equal(captureExportRecord(r,a).originalsIncluded,false);assert.equal(preferredCaptureAsset(r,{includeOriginal:true}).id,'original');});
test('SHA-256 is over exact original bytes',async()=>{assert.equal(await hashBytes(new Blob(['abc'])),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');});
