import test from 'node:test';import assert from 'node:assert/strict';
import {emptyState,WORKSPACE_KEY,validateWorkspace} from '../account-id-tool/workspace-model.js';
let db={},session={},failWrites=false,openTab=async o=>({id:1,...o}),getTab=async id=>({id,url:'https://example.test/source',title:'Synthetic page'});
globalThis.chrome={storage:{session:{async get(key){return {[key]:structuredClone(session[key])};},async set(values){Object.assign(session,structuredClone(values));}},local:{async get(key){if(key===null)return structuredClone(db);return {[key]:structuredClone(db[key])};},async set(values){await Promise.resolve();if(failWrites)throw new Error('QUOTA_BYTES exceeded');Object.assign(db,structuredClone(values));}}},tabs:{create:args=>openTab(args),get:id=>getTab(id),update:async(id,patch)=>({id,...patch}),remove:async()=>{}}};
const {dispatch,readWorkspace,openSearch,backup,importBackup,capturePage,validateBackup}=await import('../account-id-tool/workspace-store.js');
async function start(){db={};session={};failWrites=false;openTab=async o=>({id:1,...o});getTab=async id=>({id,url:'https://example.test/source',title:'Synthetic page'});const a=(await dispatch({type:'project.create',name:'Northbridge',scanName:'October review'})).result.scanId;const b=(await dispatch({type:'project.create',name:'Southridge',scanName:'Intake'})).result.scanId;return {a,b};}
test('simultaneous commands serialize without losing saved items',async()=>{const {a}=await start();await Promise.all(Array.from({length:25},(_,i)=>dispatch({type:'item.save',kind:'note',scanId:a,title:'Note '+i,body:'Synthetic note '+i})));const state=await readWorkspace();assert.equal(state.items.length,25);assert.equal(state.revision,27);validateWorkspace(state);});
test('failed persistence never reports success or poisons subsequent writes',async()=>{const {a}=await start(),before=structuredClone(db);failWrites=true;await assert.rejects(dispatch({type:'task.create',scanId:a,title:'Unwritten task'}),/QUOTA/);assert.deepEqual(db,before);failWrites=false;await dispatch({type:'task.create',scanId:a,title:'Written task'});assert.equal((await readWorkspace()).tasks.length,1);});
test('actual search command remembers its scan across delayed tab creation',async()=>{const {a,b}=await start();let release,opened=false;openTab=()=>{opened=true;return new Promise(resolve=>release=resolve);};const work=openSearch({scanId:a,provider:'google',query:'Northbridge synthetic'});while(!opened)await new Promise(r=>setImmediate(r));assert.equal((await readWorkspace()).searches.length,0);await dispatch({type:'context.select',scanId:b});release({id:1});await work;const state=await readWorkspace();assert.equal(state.searches.length,0);assert.equal(session['gather.tabContexts.v1']['1'].scanId,a);assert.doesNotMatch(JSON.stringify(db)+JSON.stringify(session),/Northbridge synthetic/);assert.equal(state.activeScanId,b);});
test('failed tab creation leaves no retained search query or event',async()=>{const {a}=await start();openTab=async()=>{throw new Error('blocked');};await assert.rejects(openSearch({scanId:a,provider:'google',query:'test'}),/could not open/);assert.equal((await readWorkspace()).searches.length,0);assert.ok(!(await readWorkspace()).activity.some(x=>x.kind.startsWith('search.')));});
test('capture uses original tab and destination even during a switch',async()=>{const {a,b}=await start();let release;getTab=id=>new Promise(resolve=>release=()=>resolve({id,url:'https://example.test/original',title:'Original'}));const pending=capturePage(a,55);while(!release)await new Promise(r=>setImmediate(r));await dispatch({type:'context.select',scanId:b});release();await pending;const state=await readWorkspace();assert.equal(state.items[0].url,'https://example.test/original');assert.equal(state.items[0].scanId,a);});
test('capture cannot silently save inaccessible pages',async()=>{await start();getTab=async()=>({id:1});await assert.rejects(capturePage(null,1),/toolbar/);assert.equal((await readWorkspace()).items.length,0);});
test('complete backup restores original workspace, legacy batches and settings into empty storage',async()=>{const {a}=await start();await dispatch({type:'item.save',kind:'note',scanId:a,title:'Synthetic','body':'Keep exactly'});db['gather.batch.fixture']={id:'fixture',createdAt:1780000000000,title:'Legacy',entries:[{url:'https://www.facebook.com/profile.php?id=9007199254740993123',id:'9007199254740993123',status:'resolved'}]};db['gather.prefs']={includeNames:false};db['gather.draft']='unfinished';const original=structuredClone(db),saved=await backup();db={};await importBackup(saved);assert.deepEqual(db,original);});
test('import with collisions adds separate copies and archives conflicting preferences',async()=>{await start();db['gather.prefs']={includeNames:true};const saved=await backup();saved.legacy['gather.prefs']={includeNames:false};const current=(await readWorkspace()).projects.length;const r=await importBackup(saved);assert.equal(r.state.projects.length,current*2);assert.deepEqual(db['gather.prefs'],{includeNames:true});const archive=Object.keys(db).find(k=>k.startsWith('gather.archive.'));assert.deepEqual(db[archive]['gather.prefs'],{includeNames:false});});
test('report files and foreign keys are rejected before import mutation',async()=>{await start();const original=structuredClone(db);assert.throws(()=>validateBackup({format:'gather-report'}));const saved=await backup();saved.legacy={unrelated:'bad'};await assert.rejects(async()=>importBackup(saved),/key/);assert.deepEqual(db,original);});
