#!/usr/bin/env python3
"""Build one static isolated-world reader from the same tested adapter modules.
No eval, runtime imports, remote code, or third-party bundler. --check is a release gate.
"""
import argparse
import re
from pathlib import Path
root = Path(__file__).resolve().parents[1] / 'account-id-tool'
modules = ['account-state', 'profile-status', 'core', 'read-profile-source']
parts = ['// Generated by scripts/build-profile-reader.py; edit the source modules, then regenerate.\n(() => {\n']
for index, name in enumerate(modules):
    code = (root / (name + '.js')).read_text()
    exports = re.findall(r'^export (?:async )?(?:function|const) (\w+)', code, re.M)
    def imports(match):
        imported, dependency = match.groups()
        if dependency not in modules[:index]:
            raise ValueError('Unexpected module dependency: ' + dependency)
        return 'const {' + imported + '} = modules[' + str(modules.index(dependency)) + '];'
    code = re.sub(r"^import \{([^}]+)\} from './([^']+)\.js';", imports, code, flags=re.M)
    code = re.sub(r'^export ', '', code, flags=re.M)
    if re.search(r'^\s*(import|export)\b', code, re.M):
        raise ValueError('Unsupported module syntax')
    if not index: parts.append('const modules = [];\n')
    parts.append('modules.push((() => {\n' + code + '\nreturn {' + ','.join(exports) + '};\n})());\n')
parts.append('''const {extractId, normalizeProfile} = modules[2];
const {readProfileSource} = modules[3];
Object.defineProperty(globalThis, '__gatherProfileReader', {configurable: true, value: async (url, source, includeName) => {
  let profile;
  try {profile = normalizeProfile(url);} catch {return {error: 'Invalid profile link.'};}
  const before = location.href;
  let result;
  if (source) {
    const snapshot = await readProfileSource();
    if (snapshot.error) return snapshot;
    result = extractId(snapshot.html, profile, snapshot.url);
  } else {
    result = extractId(document.documentElement.outerHTML.slice(0, 15000001), profile, before);
  }
  if (location.href !== before) return {error: 'The page changed during lookup. Open the intended profile and retry.'};
  if (!includeName) delete result.displayName;
  // No raw HTML, scripts, cookies, unrelated fields or case context cross back.
  return result;
}});
})();
''')
output = ''.join(parts)
parser = argparse.ArgumentParser();parser.add_argument('--check', action='store_true');args = parser.parse_args()
target = root / 'profile-reader.js'
if args.check:
    if not target.exists() or target.read_text() != output: raise SystemExit('Profile reader is stale. Run python3 scripts/build-profile-reader.py.')
else: target.write_text(output)
print('Profile reader ' + ('verified' if args.check else 'generated') + ' from local adapter sources.')
