import {captureViewer} from './capture-viewer.js';
import {retainFocus} from './workspace-focus.js';
import {request,downloadFile} from './workspace-client.js';
import {destinationLabel,WORKSPACE_KEY} from './workspace-model.js';
import {listSubjects,createSubject,renameSubject,associateSubject,selectSubject,selectedSubject,getCaptureSettings,updateCaptureSettings,listCaptures,getCapture,updateCaptureReview,getAsset,captureStats,recoverInterruptedCaptures,captureDeleteGuard,deleteCaptures} from './capture-store.js';
import {exportCapture,preferredCaptureAsset,captureExportRecord} from './capture-files.js';
import {copyCaptureImage,saveCaptureImage,printCaptureLink} from './capture-output.js';
import {historyScope,filterCaptureHistory,captureHistoryGroups} from './capture-history.js';
const popup=location.pathname.endsWith('/popup.html'),panel=new URLSearchParams(location.search).has('panel'),compact=popup||panel;
const host=document.getElementById('captureTools');
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const workspaceError=compact?null:el('p','','capture-error');if(workspaceError){workspaceError.setAttribute('role','alert');document.getElementById('workspaceStatus').append(workspaceError);}
let openedLinkedCapture=false;
let librarySerial=0,shown=12,searchText='',inspector=null,libraryStatus;
let state,scope,tabId,windowId,settings,originatingSearchId=null,subjects=[],serial=0,refreshTimer,urls=[],browse=historyScope(new URLSearchParams(location.search).get('captureScope')),subjectFilter=null,caseFilter='all',scanFilter='all',statusFilter='saved',historySubjects=new Map(),selectedCaptures=new Map();
const feedback=text=>{const target=compact?notice:libraryStatus;target.textContent=text;target.classList.remove('capture-error');};
const error=err=>{const target=compact?notice:(inspector?.querySelector('[role=alert]')||workspaceError);target.textContent=err.message||String(err);target.classList.add('capture-error');};
const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=()=>Promise.resolve().then(fn).catch(error);return b;};
const label=el('p','Active context','micro'),destination=el('p','','capture-destination'),subjectRow=el('div',undefined,'capture-controls'),subjectLabel=el('label','Subject'),subjectSelect=el('select');subjectSelect.id='captureSubject';subjectLabel.htmlFor=subjectSelect.id;subjectRow.append(subjectLabel,subjectSelect);
const mode=el('select');mode.setAttribute('aria-label','Capture mode');for(const [name,value] of [['Visible page','visible'],['Selected rectangle','selection'],['Full page (bounded)','full-page']])mode.append(new Option(name,value));
const launch=button('Capture',async()=>{if(!tabId)throw new Error('Use Gather’s toolbar or side panel on the page to capture.');const frozenTab=tabId,subjectId=subjectSelect.value||null;launch.disabled=true;try{await request('capture.start',{tabId:frozenTab,destination:{...scope,originatingSearchId},subjectId,mode:mode.value,...(reference.value?{[reference.selectedOptions[0].dataset.kind==='account'?'accountId':'sourceId']:reference.value}:{})});notice.textContent='Capture started with this destination. Keep the source tab selected until its image is taken.';if(popup)window.close();}finally{launch.disabled=false;}});
const controls=el('div',undefined,'capture-controls');controls.append(mode,launch,button('Save source',async()=>{if(!tabId)throw new Error('Open Gather on the page first.');const r=await request('workspace.capture',{tabId,scanId:scope.scanId,subjectId:subjectSelect.value||null});notice.textContent='Saved URL, title and time to '+r.result.destinationLabel+'. No image was captured.';}));
const notice=el('p','','micro');notice.setAttribute('role','status');
const refDetails=el('details'),refSummary=el('summary','Link to a saved finding (optional)'),reference=el('select');reference.setAttribute('aria-label','Capture account or source reference');refDetails.append(refSummary,reference);
host.append(label,destination,subjectRow,controls,refDetails,notice);
const gallery=document.getElementById('captureLibrary');
let list,filterMode,filterSubject,autoExport,usage,libraryCaption,moreButton,subjectManage,filterCase,filterScan,filterStatus,selectionTools,deleteSelected,exportScopeSummary;
function dialog(title,fields,onSave){
  const returnFocus=document.activeElement;const d=el('dialog'),form=el('form'),heading=el('h2',title),err=el('p','','capture-error'),buttons=el('div',undefined,'dialog-actions'),cancel=button('Cancel',()=>d.close()),save=el('button','Save','primary');save.type='submit';buttons.append(cancel,save);form.append(heading,...fields,err,buttons);d.append(form);document.body.append(d);heading.id='subject-dialog-title';d.setAttribute('aria-labelledby',heading.id);d.onclose=()=>{d.remove();if(returnFocus?.isConnected)returnFocus.focus();};form.onsubmit=async event=>{event.preventDefault();save.disabled=true;try{await onSave(new FormData(form));d.close();await refresh();}catch(e){err.textContent=e.message;}finally{save.disabled=false;}};d.showModal();form.querySelector('input,select,textarea')?.focus();
}
function field(caption,name,value='',max=100){const label=el('label',caption,'capture-field'),input=el('input');input.name=name;input.value=value;input.maxLength=max;input.required=true;label.append(input);return label;}
async function editSubject(rename=false){const frozen={...scope},current=subjects.find(s=>s.id===subjectSelect.value);if(rename&&!current)throw new Error('Choose a subject first.');dialog(rename?'Rename '+settings.subjectLabel:'New '+settings.subjectLabel,[field('Name','name',current?.name||'')],async data=>{const subject=rename?await renameSubject(current.id,data.get('name')):await createSubject({projectId:frozen.projectId,name:data.get('name')});await selectSubject(frozen.scanId,subject.id,frozen.projectId);});}
if(!compact){
  subjectManage=el('div',undefined,'capture-controls');document.getElementById('subjectManagement').append(subjectManage);
  subjectManage.append(button('New subject',()=>editSubject()),button('Rename subject',()=>editSubject(true)),button('Display label',()=>{const projectId=scope.projectId;dialog('Subject display label',[field('Label, for example Subject or SOC','label',settings.subjectLabel,30)],data=>updateCaptureSettings({subjectLabel:data.get('label')},{projectId}));}));
  const associate=button('Associate account observations',()=>{const frozenState=state;const subject=subjects.find(s=>s.id===subjectSelect.value);if(!subject)throw new Error('Choose a subject first.');const choices=el('div');for(const item of state.items.filter(i=>i.projectId===scope.projectId&&i.kind==='account')){const l=el('label',undefined,'capture-check'),input=el('input');input.type='checkbox';input.name='observation';input.value=item.id;input.checked=subject.accountObservationIds.includes(item.id);l.append(input,document.createTextNode(item.title+' · '+(item.entry.id||'Unresolved')+' · '+new Date(item.createdAt).toLocaleString()));choices.append(l);}if(!choices.children.length)choices.append(el('p','Save an account observation in this project first.'));dialog('Explicit account associations',[el('p','These assignments do not identify or merge people.','quiet'),choices],data=>associateSubject(subject.id,data.getAll('observation'),frozenState));});subjectManage.append(associate);
  const heading=el('div',undefined,'capture-library-heading'),headingText=el('div');libraryCaption=el('p','','quiet');headingText.append(el('h2','Capture history'),libraryCaption);heading.append(headingText);
  const exportTools=el('details',undefined,'capture-export-menu');exportScopeSummary=el('summary','Export scan…');exportTools.append(exportScopeSummary);const exportActions=el('div',undefined,'export-actions');
  exportActions.append(button('Export included images',async()=>{const frozenScan=scope.scanId,frozenLabel=destinationLabel(state,frozenScan);const selected=await listCaptures({scanId:frozenScan}),included=selected.filter(c=>c.savedState==='saved'&&c.included!==false&&c.review!=='excluded');if(!included.length){feedback('No captures selected for export in '+frozenLabel+'. Open a capture to include it after review.');return;}if(!confirm('Export '+included.length+' included capture(s) from '+frozenLabel+' to Downloads?'))return;let failed=0;for(const capture of included){try{await exportCapture(capture.id);}catch{failed++;}}feedback('Processed '+included.length+' captures from '+frozenLabel+'; '+failed+' exports failed. Saved images remain in Gather.');await renderLibrary();}));
  exportActions.append(button('Review evidence sheet ↗',()=>chrome.tabs.create({url:chrome.runtime.getURL('evidence.html?scan='+scope.scanId)})));exportTools.append(exportActions,el('p','Exports included captures from the scan shown in the workspace header.','micro'));heading.append(exportTools);gallery.append(heading);
  const filters=el('div',undefined,'capture-toolbar'),search=el('input');search.type='search';search.placeholder='Find captures…';search.setAttribute('aria-label','Find captures');search.oninput=()=>{searchText=search.value;clearSelection();shown=12;renderLibrary().catch(error);};
  filterMode=el('select');filterMode.setAttribute('aria-label','Browse captures');filterMode.append(new Option('This scan','scan'),new Option('This case','case'),new Option('All cases','all'),new Option('Subject across this case','subject'));filterMode.value=browse;filterSubject=el('select');filterSubject.setAttribute('aria-label','Browse subject');filterSubject.hidden=browse!=='subject';filterCase=el('select');filterCase.setAttribute('aria-label','Filter capture case');filterScan=el('select');filterScan.setAttribute('aria-label','Filter capture scan');filterStatus=el('select');filterStatus.setAttribute('aria-label','Filter capture status');filterStatus.append(new Option('Saved images','saved'),new Option('All captures & attempts','all'),new Option('Needs attention','attention'));filterStatus.value=statusFilter;const filterDetails=el('details',undefined,'capture-filter-options'),filterFields=el('div',undefined,'capture-filter-fields');filterDetails.append(el('summary','Filters'),filterFields);for(const [caption,select]of [['Subject',filterSubject],['Case',filterCase],['Scan',filterScan],['Status',filterStatus]]){const label=el('label',caption);label.append(select);filterFields.append(label);}filters.append(search,filterMode,filterDetails);gallery.append(filters);document.addEventListener('pointerdown',event=>{if(filterDetails.open&&!filterDetails.contains(event.target))filterDetails.open=false;});filterDetails.addEventListener('keydown',event=>{if(event.key==='Escape'){event.stopPropagation();filterDetails.open=false;filterDetails.querySelector('summary').focus();}});
  filterMode.onchange=()=>{browse=filterMode.value;filterSubject.hidden=browse!=='subject';filterSubject.parentElement.hidden=browse!=='subject';if(browse==='subject')filterDetails.open=true;scanFilter='all';clearSelection();shown=12;renderLibrary().catch(error);};filterSubject.onchange=()=>{subjectFilter=filterSubject.value||null;clearSelection();shown=12;renderLibrary().catch(error);};
  filterCase.onchange=()=>{caseFilter=filterCase.value;scanFilter='all';clearSelection();shown=12;renderLibrary().catch(error);};filterScan.onchange=()=>{scanFilter=filterScan.value;clearSelection();shown=12;renderLibrary().catch(error);};filterStatus.onchange=()=>{statusFilter=filterStatus.value;clearSelection();shown=12;renderLibrary().catch(error);};
  selectionTools=el('div',undefined,'capture-selection-tools');selectionTools.hidden=true;deleteSelected=button('Delete selected…',()=>removeCaptures([...selectedCaptures.values()]));deleteSelected.className='danger';selectionTools.append(deleteSelected,button('Clear selection',()=>clearSelection()));gallery.append(selectionTools);
  libraryStatus=el('p','','capture-library-status');libraryStatus.setAttribute('role','status');gallery.append(libraryStatus);
  const prefs=document.getElementById('capturePreferences'),check=el('label',undefined,'capture-check');autoExport=el('input');autoExport.type='checkbox';autoExport.id='automaticCaptureExport';check.append(autoExport,document.createTextNode('Automatically export new captures to Downloads / Gather'));usage=el('p','','micro');prefs.append(el('h3','Capture exports'),check,el('p','Exports use subfolders in your browser’s Downloads directory. Failed exports keep the image in Gather and offer Retry.','quiet'),usage);
  autoExport.onchange=()=>updateCaptureSettings({automaticExport:autoExport.checked}).catch(e=>{autoExport.checked=!autoExport.checked;usage.textContent=e.message;});
  list=el('div',undefined,'capture-groups');gallery.append(list);moreButton=button('Show more captures',()=>{shown+=12;renderLibrary().catch(error);});moreButton.className='capture-more';moreButton.hidden=true;gallery.append(moreButton);

}
subjectSelect.onchange=()=>selectSubject(scope.scanId,subjectSelect.value||null,scope.projectId).then(()=>{notice.textContent='Future captures use '+(subjectSelect.selectedOptions[0]?.textContent||'Unassigned')+'.';}).catch(error);
function captureHost(record){try{return new URL(record.source.url).hostname;}catch{return record.source.url;}}
function filing(record){return destinationLabel(state,record.scanId)+' / '+(historySubjects.get(record.subjectId)?.name||subjects.find(s=>s.id===record.subjectId)?.name||record.context.subjectName||'Unassigned');}
function savedLabel(record){return record.savedState==='saved'?'Saved in Gather':'Image not saved';}
function folderLabel(record){return record.export?.status==='exported'?'Exported to folder':record.export?.status==='failed'?'Folder export failed':'Not exported';}
async function openCapture(id){
  const record=await getCapture(id);if(!record)throw new Error('This capture is no longer available.');
  inspector?.close();const d=el('dialog',undefined,'capture-inspector'),title=el('h2',record.source.title||captureHost(record)),heading=el('div',undefined,'inspector-heading'),close=button('Close',()=>d.close());
  title.id='capture-inspector-title';d.dataset.captureId=id;d.setAttribute('aria-labelledby',title.id);heading.append(title,close);d.append(heading,el('p',filing(record),'quiet'),el('p',savedLabel(record)+' · '+folderLabel(record)+' · '+record.mode+' · '+record.status,'micro'));
  const err=el('p','','capture-error');err.setAttribute('role','alert');d.append(err);let previewUrl=null;
  const controls=el('div',undefined,'inspector-controls');
  if(record.savedState==='saved'){
    const viewer=captureViewer('Selected image for '+(record.source.title||captureHost(record))),image=viewer.image;image.className='inspector-image';d.append(viewer.element,el('p',preferredCaptureAsset(record)?.role==='derivative'?'Viewing the selected derivative. Original pixels remain stored separately.':'Viewing the saved original image. Review its contents before sharing.','micro'));
    const review=el('select');review.setAttribute('aria-label','Review capture '+record.id);for(const [value,label] of [['unreviewed','Unreviewed'],['reviewed','Reviewed'],['follow-up','Needs follow-up'],['excluded','Excluded']])review.append(new Option(label,value));review.value=record.review||'unreviewed';
    const includeLabel=el('label',undefined,'capture-check'),include=el('input');include.type='checkbox';include.checked=record.included!==false;include.disabled=record.review==='excluded';includeLabel.append(include,document.createTextNode('Include in scan export'));
    review.onchange=async()=>{const before=record.review;try{const changed=await updateCaptureReview(record.id,{review:review.value,...(review.value==='excluded'?{included:false}:{})});Object.assign(record,changed);include.disabled=review.value==='excluded';if(include.disabled)include.checked=false;}catch(e){review.value=before;err.textContent=e.message;}};
    include.onchange=()=>updateCaptureReview(record.id,{included:include.checked}).then(changed=>Object.assign(record,changed)).catch(e=>{include.checked=!include.checked;err.textContent=e.message;});controls.append(review,includeLabel);d.append(controls);
    const actions=el('div',undefined,'export-actions');const copy=button('Copy image',async()=>{copy.disabled=true;try{await copyCaptureImage(record.id);err.textContent='Image copied to clipboard.';}finally{copy.disabled=false;}});copy.className='primary';actions.append(copy,button('Save image…',async()=>{await saveCaptureImage(record.id,'png');err.textContent='Image downloaded.';}),button('Print / Save PDF ↗',()=>chrome.tabs.create({url:printCaptureLink(record.id)})),button('Edit image ↗',()=>chrome.tabs.create({url:chrome.runtime.getURL('capture-edit.html?id='+record.id)})),button(record.export?.status==='failed'?'Retry folder export':'Export to folder',async()=>{try{await exportCapture(record.id);err.textContent='';feedback('Capture exported to folder.');d.close();await renderLibrary();}catch(e){err.textContent=e.message;}}));const more=el('details',undefined,'capture-image-options');more.append(el('summary','More image options'),button('Save JPEG…',async()=>{await saveCaptureImage(record.id,'jpg');err.textContent='JPEG downloaded.';}),actions.lastChild);d.insertBefore(actions,viewer.element);d.insertBefore(more,viewer.element);
    d.refreshImage=async()=>{const current=await getCapture(id);if(!d.open)return;if(!current){d.close();feedback('This capture was deleted from Gather.');return;}if(preferredCaptureAsset(current)?.id!==preferredCaptureAsset(record)?.id){try{const asset=await getAsset(preferredCaptureAsset(current).id,{verify:true});if(!d.open)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(asset.blob);image.src=previewUrl;Object.assign(record,current);err.textContent='Updated saved image.';}catch(e){image.removeAttribute('src');err.textContent=e.message;}}};
    getAsset(preferredCaptureAsset(record)?.id,{verify:true}).then(asset=>{if(!d.open)return;previewUrl=URL.createObjectURL(asset.blob);image.src=previewUrl;}).catch(e=>{if(d.open)err.textContent=e.message;});
  }else d.append(el('p',record.error||'This capture has no saved image.','capture-error'));
  const details=el('details',undefined,'inspector-details');details.append(el('summary','Source & capture details'),el('p',record.source.url),el('p',record.evidenceId||'E-'+record.id),el('p','Captured '+new Date(record.startedAt).toLocaleString()+' · '+(record.timezone||'local time')),el('p','Destination at capture: '+[record.context.projectName,record.context.scanName,record.context.subjectName].filter(Boolean).join(' / ')),el('p',(record.limitations||[]).join('\n')),el('p','The original image is preserved. Exports use the selected derivative when one exists. Hashes verify bytes, not authenticity or identity.'));
  if(record.assets?.length){const asset=preferredCaptureAsset(record);details.append(el('p','Selected asset: '+asset.role+' · '+asset.bytes+' bytes'),el('p','SHA-256: '+asset.sha256));}if(record.savedState==='saved')details.append(button('Download capture record',()=>downloadFile('Gather-capture-'+record.id+'.json',captureExportRecord(record,preferredCaptureAsset(record)))));d.append(details);const remove=button('Delete capture…',async()=>{if(await removeCaptures([record]))d.close();});remove.className='danger';remove.disabled=record.status==='capturing'||record.export?.status==='exporting';d.append(remove);
  inspector=d;d.onclose=()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);d.remove();if(inspector===d){inspector=null;}const target=[...list.querySelectorAll('[data-capture-id]')].find(e=>e.dataset.captureId===id)?.querySelector('button');(target||document.getElementById('tab-captures')).focus();};document.body.append(d);d.showModal();close.focus();
}
function clearSelection(){selectedCaptures.clear();if(selectionTools)selectionTools.hidden=true;list?.querySelectorAll('.capture-select').forEach(input=>input.checked=false);}
function updateSelection(){selectionTools.hidden=!selectedCaptures.size;deleteSelected.textContent='Delete selected ('+selectedCaptures.size+')…';}
async function removeCaptures(records){
  const guard=captureDeleteGuard(records),places=[...new Set(records.map(filing))],summary=places.slice(0,4).join('\n')+(places.length>4?'\n+ '+(places.length-4)+' more destinations':'');
  if(!confirm('Delete '+records.length+' capture'+(records.length===1?'':'s')+' and all their stored images from Gather?\n\n'+summary+'\n\nThis cannot be undone. Cases, subjects and other captures remain. Files already downloaded and clipboard contents are separate.'))return false;
  const result=await deleteCaptures(guard);clearSelection();feedback(result.captures+' capture'+(result.captures===1?'':'s')+' deleted from Gather.');await renderLibrary();return true;
}
async function renderLibrary(){
  if(!list||!scope||document.body.dataset.section!=='captures')return;
  const token=++librarySerial,frozen={...scope},all=await listCaptures();
  const projects=[...new Set(all.map(r=>r.projectId).filter(Boolean))];const names=await Promise.all(projects.map(id=>listSubjects(id)));
  if(token!==librarySerial)return;historySubjects=new Map(names.flat().map(s=>[s.id,s]));
  const caseIds=new Set(all.map(r=>r.projectId));if(caseFilter!=='all'&&caseFilter!=='inbox'&&!caseIds.has(caseFilter))caseFilter='all';
  filterCase.replaceChildren(new Option('Any case','all'),...(caseIds.has(null)?[new Option('Inbox','inbox')]:[]),...state.projects.filter(p=>caseIds.has(p.id)).map(p=>new Option(p.name+' ('+all.filter(r=>r.projectId===p.id).length+')',p.id)));filterCase.value=caseFilter;filterCase.hidden=browse!=='all';filterCase.parentElement.hidden=filterCase.hidden;filterSubject.parentElement.hidden=browse!=='subject';
  const caseRecords=all.filter(r=>browse==='all'?(caseFilter==='all'||r.projectId===(caseFilter==='inbox'?null:caseFilter)):r.projectId===frozen.projectId),scanIds=new Set(caseRecords.map(r=>r.scanId));
  if(scanFilter!=='all'&&!scanIds.has(scanFilter==='inbox'?null:scanFilter))scanFilter='all';
  filterScan.replaceChildren(new Option('All scans','all'),...(scanIds.has(null)?[new Option('Inbox','inbox')]:[]),...state.scans.filter(s=>scanIds.has(s.id)).map(s=>new Option(browse==='all'&&caseFilter==='all'?destinationLabel(state,s.id):s.name,s.id)));filterScan.value=scanFilter;filterScan.hidden=browse==='scan';filterScan.parentElement.hidden=filterScan.hidden;
  const records=filterCaptureHistory(all,{scope:browse,...frozen,subjectId:subjectFilter,caseFilter,scanFilter,status:statusFilter,query:searchText,label:filing});
  const ids=new Set(records.map(r=>r.id));for(const id of selectedCaptures.keys())if(!ids.has(id))selectedCaptures.delete(id);updateSelection();
  const restoreFocus=retainFocus(list);try{
    for(const url of urls)URL.revokeObjectURL(url);urls=[];list.replaceChildren();libraryCaption.textContent=records.length+' capture'+(records.length===1?'':'s')+' · '+(browse==='scan'?destinationLabel(state,frozen.scanId):browse==='all'?'All cases':browse==='case'?state.projects.find(p=>p.id===frozen.projectId)?.name||'Inbox':'Selected subject across this case');moreButton.hidden=records.length<=shown;
    if(!records.length){const empty=el('div',undefined,'empty');empty.append(el('strong',searchText||statusFilter!=='saved'?'No matching captures':'No captures here yet'),el('span','Use Gather on a page to capture its image, or choose another view.'));list.append(empty);return;}
    for(const group of captureHistoryGroups(records.slice(0,shown))){
      const section=el('section',undefined,'capture-group'),grid=el('div',undefined,'capture-grid');section.append(el('h3',destinationLabel(state,group.scanId),'capture-group-title'),grid);list.append(section);
      for(const record of group.records){
        const card=el('article',undefined,'capture-card');card.dataset.captureId=record.id;card.dataset.focusKey=record.id;const open=button('',()=>openCapture(record.id));open.className='capture-open';open.setAttribute('aria-label','Open capture '+(record.source.title||captureHost(record)));const figure=el('div',undefined,'capture-image'),info=el('div',undefined,'capture-card-info');
        info.append(el('h3',record.source.title||captureHost(record)),el('p',captureHost(record)+' · '+new Date(record.startedAt).toLocaleString()),el('p',historySubjects.get(record.subjectId)?.name||record.context.subjectName||'Unassigned','capture-subject'),el('span',record.review==='reviewed'?'Reviewed':record.review==='excluded'?'Excluded':record.review==='follow-up'?'Needs follow-up':'Unreviewed','capture-review'));open.append(figure,info);
        const selectLabel=el('label',undefined,'capture-card-selection'),select=el('input');select.type='checkbox';select.className='capture-select';select.setAttribute('aria-label','Select capture '+(record.source.title||captureHost(record)));select.checked=selectedCaptures.has(record.id);select.disabled=record.status==='capturing'||record.export?.status==='exporting';select.onchange=()=>{if(select.checked)selectedCaptures.set(record.id,record);else selectedCaptures.delete(record.id);updateSelection();};selectLabel.append(select,document.createTextNode('Select'));card.append(open,el('p',savedLabel(record)+' · '+folderLabel(record),'capture-state'),selectLabel);grid.append(card);
        if(record.status!=='complete')card.append(el('p',record.status+(record.error?' · '+record.error:''),'capture-error'));if(record.export?.status==='failed')card.append(el('p',record.export.error||'Open capture to retry export.','capture-error'));
        if(record.savedState==='saved'){
          const image=el('img');image.alt='';image.loading='lazy';figure.append(image);
          try{const asset=await getAsset(preferredCaptureAsset(record)?.id,{verify:true});if(token!==librarySerial)return;const url=URL.createObjectURL(asset.blob);urls.push(url);image.src=url;}catch(e){figure.replaceChildren(el('span','Image unavailable','quiet'));card.append(el('p',e.message,'capture-error'));}
        }else figure.append(el('span','Image unavailable','quiet'));
      }
    }
  }finally{restoreFocus();}
}
async function refresh(){
  const ticket=++serial,nextState=(await request('workspace.state')).state;if(ticket!==serial)return;state=nextState;let scanId=state.activeScanId,nextSearchId=null;
  if(compact){const tab=(await chrome.tabs.query({active:true,windowId}))[0];tabId=tab?.id;if(tabId){const current=await request('workspace.tabContext',{tabId});scanId=current.context.scanId;nextSearchId=current.context.originatingSearchId||null;}}
  if(ticket!==serial)return;
  const previousScan=scope?.scanId;const scan=state.scans.find(s=>s.id===scanId);scope={scanId,projectId:scan?.projectId||null};originatingSearchId=nextSearchId;
  if(!compact&&previousScan!==scanId){if(browse!=='all'){clearSelection();scanFilter='all';}shown=12;libraryStatus.textContent='';inspector?.close();}
  const nextValues=await Promise.all([getCaptureSettings(scope.projectId),listSubjects(scope.projectId)]);if(ticket!==serial)return;[settings,subjects]=nextValues;
  const selected=await selectedSubject(scanId);if(ticket!==serial)return;destination.textContent=destinationLabel(state,scanId);subjectLabel.textContent=settings.subjectLabel;subjectSelect.replaceChildren(new Option('Unassigned',''),...subjects.map(s=>new Option(s.name===s.roleId?s.roleId:s.name+' · '+s.roleId,s.id)));subjectSelect.value=selected||'';subjectSelect.disabled=!scope.projectId;
  for(const b of (subjectManage||subjectRow).querySelectorAll('button'))b.disabled=!scope.projectId||(['Rename subject','Associate account observations'].includes(b.textContent)&&!selected);
  controls.hidden=!compact;refDetails.hidden=!compact;launch.disabled=!tabId;
  reference.replaceChildren(new Option('No saved finding',''));for(const item of state.items.filter(i=>i.projectId===scope.projectId&&['account','source'].includes(i.kind))){const o=new Option(item.title,item.id);o.dataset.kind=item.kind;reference.append(o);}
  if(!compact){exportScopeSummary.textContent='Export '+destinationLabel(state,scope.scanId)+'…';notice.textContent='';autoExport.checked=settings.automaticExport;filterSubject.replaceChildren(new Option('Unassigned',''),...subjects.map(s=>new Option(s.name===s.roleId?s.roleId:s.name+' · '+s.roleId,s.id)));if(!subjects.some(s=>s.id===subjectFilter))subjectFilter=null;filterSubject.value=subjectFilter||'';const stats=await captureStats();await inspector?.refreshImage?.();usage.textContent=(stats.bytes/1048576).toFixed(1)+' / '+(stats.limitBytes/1048576)+' MiB in Gather capture storage. Browser storage can be cleared or evicted; keep image backups.';await renderLibrary();if(!openedLinkedCapture&&!document.querySelector('.layout').inert&&document.body.dataset.section==='captures'){const link=new URLSearchParams(location.search),id=link.get('capture'),scanId=link.get('scan')==='inbox'?null:link.get('scan');if(id&&scope.scanId===scanId){openedLinkedCapture=true;const record=await getCapture(id);if(!record||record.scanId!==scope.scanId)throw new Error('This capture is no longer in the requested scan.');await openCapture(id);}}}
}
if(!compact)document.addEventListener('gather:view-changed',event=>{if(event.detail==='captures')renderLibrary().catch(error);else{librarySerial++;for(const url of urls)URL.revokeObjectURL(url);urls=[];}});
function schedule(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(error),50);}
async function init(){if(!globalThis.chrome?.runtime?.id)return;windowId=(await chrome.windows.getCurrent()).id;chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[WORKSPACE_KEY]||area==='session'&&(changes['gather.tabContexts.v1']||changes['gather.hideFriendlyLabels']||Object.keys(changes).some(k=>k.startsWith('gather.case.'))))schedule();});if(compact)chrome.tabs.onActivated.addListener(schedule);window.addEventListener('focus',schedule);document.addEventListener('gather:captures-changed',schedule);document.addEventListener('gather:workspace-ready',schedule);if(globalThis.BroadcastChannel){const channel=new BroadcastChannel('gather-captures');channel.onmessage=schedule;window.addEventListener('pagehide',()=>channel.close());}const lock=(await chrome.storage.session.get('gather.captureLock'))['gather.captureLock'];let activeIds=[];if(lock){try{await chrome.windows.get(lock.windowId);activeIds=[lock.launchId];}catch{}}await recoverInterruptedCaptures({olderThan:Date.now(),activeIds});await refresh();}
init().catch(error);
