import {getCapture,getAsset,addCaptureDerivative} from './capture-store.js';
import {preferredCaptureAsset} from './capture-files.js';
import {selectionBounds} from './capture-engine.js';
const $=id=>document.getElementById(id);let record,parent,bitmap,operations=[];
const status=text=>$('editStatus').textContent=text;
function rect(){return selectionBounds({x:Number($('redactX').value),y:Number($('redactY').value),width:Number($('redactWidth').value),height:Number($('redactHeight').value)},$('editCanvas').width,$('editCanvas').height);}
function render(){const canvas=$('editCanvas');canvas.width=bitmap.width;canvas.height=bitmap.height;let ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0);for(const op of operations){if(op.type==='redact'){ctx.fillStyle='#000';ctx.fillRect(op.x,op.y,op.width,op.height);}else{const copy=document.createElement('canvas');copy.width=op.width;copy.height=op.height;copy.getContext('2d').drawImage(canvas,op.x,op.y,op.width,op.height,0,0,op.width,op.height);canvas.width=op.width;canvas.height=op.height;ctx=canvas.getContext('2d');ctx.drawImage(copy,0,0);}}}
function add(type){try{operations.push({type,...rect()});render();status(operations.length+' edit(s) in this derivative. Original pixels are unchanged.');}catch(e){status(e.message);}}
$('redactForm').onsubmit=event=>{event.preventDefault();add('redact');};$('cropDerivative').onclick=()=>add('crop');$('undoDerivative').onclick=()=>{operations.pop();render();};$('closeDerivative').onclick=()=>window.close();
$('saveDerivative').onclick=async()=>{const button=$('saveDerivative');button.disabled=true;try{if(!operations.length&&!$('derivativeNote').value.trim())throw new Error('Add a crop, redaction or caption first.');const blob=await new Promise((resolve,reject)=>$('editCanvas').toBlob(b=>b?resolve(b):reject(new Error('Image encoding failed.')),'image/png'));record=await addCaptureDerivative(record.id,{blob,parentAssetId:parent.id,kind:operations.some(o=>o.type==='redact')?'redacted':operations.length?'cropped':'annotated',operations:{edits:operations,dimensions:{width:$('editCanvas').width,height:$('editCanvas').height}},annotation:$('derivativeNote').value});status('Saved derivative in Gather. Folder export now uses this image. Unredacted originals remain in all-work backups.');}catch(e){status(e.message);}finally{button.disabled=false;}};
async function init(){record=await getCapture(new URLSearchParams(location.search).get('id'));if(!record||record.savedState!=='saved')throw new Error('Choose a saved capture in Workspace.');parent=preferredCaptureAsset(record);bitmap=await createImageBitmap((await getAsset(parent.id,{verify:true})).blob);$('editSource').textContent=record.source.title+' · '+record.source.url;render();}
window.addEventListener('pagehide',()=>bitmap?.close());init().catch(e=>{status(e.message);document.querySelectorAll('button,input,textarea').forEach(n=>n.disabled=true);});
