import {request,downloadFile} from './workspace-client.js';
import {destinationLabel,WORKSPACE_KEY} from './workspace-model.js';
import {listSubjects,createSubject,renameSubject,associateSubject,selectSubject,selectedSubject,getCaptureSettings,updateCaptureSettings,listCaptures,updateCaptureReview,getAsset,captureStats,recoverInterruptedCaptures} from './capture-store.js';
import {exportCapture,preferredCaptureAsset,captureExportRecord} from './capture-files.js';
const popup=location.pathname.endsWith('/popup.html'),panel=new URLSearchParams(location.search).has('panel'),compact=popup||panel;
const host=document.getElementById('captureTools');
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let state,scope,tabId,windowId,settings,originatingSearchId=null,subjects=[],serial=0,refreshTimer,urls=[],browse='scan',subjectFilter=null;
const error=err=>{notice.textContent=err.message||String(err);notice.className='micro capture-error';};
const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=()=>Promise.resolve().then(fn).catch(error);return b;};
const label=el('p','Active context','micro'),destination=el('p','','capture-destination'),subjectRow=el('div',undefined,'capture-controls'),subjectLabel=el('label','Subject'),subjectSelect=el('select');subjectSelect.id='captureSubject';subjectLabel.htmlFor=subjectSelect.id;subjectRow.append(subjectLabel,subjectSelect);
const mode=el('select');mode.setAttribute('aria-label','Capture mode');for(const [name,value] of [['Visible page','visible'],['Selected rectangle','selection'],['Full page (bounded)','full-page']])mode.append(new Option(name,value));
const launch=button('Capture',async()=>{if(!tabId)throw new Error('Use Gather’s toolbar or side panel on the page to capture.');const frozenTab=tabId,subjectId=subjectSelect.value||null;launch.disabled=true;try{await request('capture.start',{tabId:frozenTab,destination:{...scope,originatingSearchId},subjectId,mode:mode.value,...(reference.value?{[reference.selectedOptions[0].dataset.kind==='account'?'accountId':'sourceId']:reference.value}:{})});notice.textContent='Capture started with this destination. Keep the source tab selected until its image is taken.';if(popup)window.close();}finally{launch.disabled=false;}});
const controls=el('div',undefined,'capture-controls');controls.append(mode,launch,button('Save metadata only',async()=>{if(!tabId)throw new Error('Open Gather on the page first.');const r=await request('workspace.capture',{tabId,scanId:scope.scanId,subjectId:subjectSelect.value||null});notice.textContent='Saved URL, title and time to '+r.result.destinationLabel+'. No image was captured.';}));
const notice=el('p','','micro');notice.setAttribute('role','status');
const refDetails=el('details'),refSummary=el('summary','Link to a saved finding (optional)'),reference=el('select');reference.setAttribute('aria-label','Capture account or source reference');refDetails.append(refSummary,reference);
host.append(label,destination,subjectRow,controls,refDetails,notice);
const gallery=document.getElementById('captureLibrary');
let list,filterMode,filterSubject,autoExport,usage;
function dialog(title,fields,onSave){
  const d=el('dialog'),form=el('form'),heading=el('h2',title),err=el('p','','capture-error'),buttons=el('div',undefined,'dialog-actions'),cancel=button('Cancel',()=>d.close()),save=el('button','Save','primary');save.type='submit';buttons.append(cancel,save);form.append(heading,...fields,err,buttons);d.append(form);document.body.append(d);d.onclose=()=>d.remove();form.onsubmit=async event=>{event.preventDefault();save.disabled=true;try{await onSave(new FormData(form));d.close();await refresh();}catch(e){err.textContent=e.message;}finally{save.disabled=false;}};d.showModal();form.querySelector('input,select,textarea')?.focus();
}
function field(caption,name,value='',max=100){const label=el('label',caption,'capture-field'),input=el('input');input.name=name;input.value=value;input.maxLength=max;input.required=true;label.append(input);return label;}
async function editSubject(rename=false){const current=subjects.find(s=>s.id===subjectSelect.value);if(rename&&!current)throw new Error('Choose a subject first.');dialog(rename?'Rename '+settings.subjectLabel:'New '+settings.subjectLabel,[field('Name','name',current?.name||'')],async data=>{const subject=rename?await renameSubject(current.id,data.get('name')):await createSubject({projectId:scope.projectId,name:data.get('name')});await selectSubject(scope.scanId,subject.id,scope.projectId);});}
if(!compact){
  subjectRow.append(button('New',()=>editSubject()),button('Rename',()=>editSubject(true)),button('Display label',()=>dialog('Subject display label',[field('Label, for example Subject or SOC','label',settings.subjectLabel,30)],data=>updateCaptureSettings({subjectLabel:data.get('label')},{projectId:scope.projectId}))));
  const associate=button('Associate account observations',()=>{const subject=subjects.find(s=>s.id===subjectSelect.value);if(!subject)throw new Error('Choose a subject first.');const choices=el('div');for(const item of state.items.filter(i=>i.projectId===scope.projectId&&i.kind==='account')){const l=el('label',undefined,'capture-check'),input=el('input');input.type='checkbox';input.name='observation';input.value=item.id;input.checked=subject.accountObservationIds.includes(item.id);l.append(input,document.createTextNode(item.title+' · '+(item.entry.id||'Unresolved')+' · '+new Date(item.createdAt).toLocaleString()));choices.append(l);}if(!choices.children.length)choices.append(el('p','Save an account observation in this project first.'));dialog('Explicit account associations',[el('p','These assignments do not identify or merge people.','quiet'),choices],data=>associateSubject(subject.id,data.getAll('observation'),state));});subjectRow.append(associate);
  gallery.append(el('h2','Captures'));
  const filters=el('div',undefined,'capture-controls');filterMode=el('select');filterMode.setAttribute('aria-label','Browse captures');filterMode.append(new Option('This scan','scan'),new Option('Subject across this project','subject'));filterSubject=el('select');filterSubject.setAttribute('aria-label','Browse subject');filterSubject.hidden=true;filters.append(filterMode,filterSubject);filters.append(button('Export this scan’s captures',async()=>{const selected=await listCaptures({scanId:scope.scanId});const included=selected.filter(c=>c.savedState==='saved'&&c.included!==false&&c.review!=='excluded');let failed=0;for(const capture of included){try{await exportCapture(capture.id);}catch{failed++;}}notice.textContent=included.length+' capture(s) processed for this scan; '+failed+' export(s) failed and can be retried. Originals are excluded when a derivative is selected.';await renderLibrary();}));filters.append(button('Review evidence sheet ↗',()=>chrome.tabs.create({url:chrome.runtime.getURL('evidence.html?scan='+scope.scanId)})));gallery.append(filters);
  filterMode.onchange=()=>{browse=filterMode.value;filterSubject.hidden=browse!=='subject';renderLibrary().catch(error);};filterSubject.onchange=()=>{subjectFilter=filterSubject.value||null;renderLibrary().catch(error);};
  const prefs=el('details'),summary=el('summary','Folder export and storage'),check=el('label',undefined,'capture-check');autoExport=el('input');autoExport.type='checkbox';autoExport.id='automaticCaptureExport';check.append(autoExport,document.createTextNode('Automatically export new captures to Downloads / Gather'));usage=el('p','','micro');prefs.append(summary,check,el('p','Gather creates subfolders inside the browser’s Downloads directory. It cannot choose an arbitrary absolute path. Export failure never deletes the saved image.','micro'),usage);gallery.append(prefs);
  autoExport.onchange=()=>updateCaptureSettings({automaticExport:autoExport.checked}).catch(error);
  list=el('div',undefined,'cards capture-list');gallery.append(list);
}
subjectSelect.onchange=()=>selectSubject(scope.scanId,subjectSelect.value||null,scope.projectId).then(()=>{notice.textContent='Future captures use '+(subjectSelect.selectedOptions[0]?.textContent||'Unassigned')+'.';}).catch(error);
async function renderLibrary(){
  if(!list||!scope)return;
  const thisRender=serial;const records=await listCaptures(browse==='scan'?{scanId:scope.scanId}:{projectId:scope.projectId,subjectId:subjectFilter});
  if(thisRender!==serial)return;for(const url of urls)URL.revokeObjectURL(url);urls=[];list.replaceChildren();
  if(!records.length){list.append(el('p','No captures here yet. Use Gather on a page to save its image. Include captures deliberately after review.','quiet'));return;}
  for(const record of records){const card=el('article',undefined,'card');card.dataset.captureId=record.id;card.append(el('h3',record.source.title||record.source.url),el('p',destinationLabel(state,record.scanId)+' / '+(subjects.find(s=>s.id===record.subjectId)?.name||record.context.subjectName),'quiet'),el('p',record.evidenceId||'E-'+record.id,'micro'),el('p',new Date(record.startedAt).toLocaleString()+' · '+record.mode+' · '+record.status,'micro'));
    const saved=record.savedState==='saved';card.append(el('p',saved?'Saved in Gather':'Image not saved · '+(record.error||record.status)));
    const exportState=record.export?.status;card.append(el('p',exportState==='exported'?'Exported to folder':exportState==='failed'?'Folder export failed · '+record.export.error:'Folder: '+(exportState||'not exported'),'micro'));
    if(saved){const image=el('img');image.alt='Saved '+record.mode+' capture';image.className='capture-thumb';image.loading='lazy';card.append(image);
      try{const asset=await getAsset(preferredCaptureAsset(record)?.id,{verify:true});if(thisRender!==serial)return;const url=URL.createObjectURL(asset.blob);urls.push(url);image.src=url;}catch(e){card.append(el('p',e.message,'capture-error'));}
      const actions=el('div',undefined,'card-controls');actions.append(button('Crop / redact / caption',()=>chrome.tabs.create({url:chrome.runtime.getURL('capture-edit.html?id='+record.id)})),button(exportState==='failed'?'Retry folder export':'Export to folder',async()=>{await exportCapture(record.id);await renderLibrary();}),button('Capture record',()=>downloadFile('Gather-capture-'+record.id+'.json',captureExportRecord(record,preferredCaptureAsset(record)))));const review=el('select');review.setAttribute('aria-label','Review capture '+record.id);for(const value of ['unreviewed','reviewed','follow-up','excluded'])review.append(new Option(value,value));review.value=record.review||'unreviewed';review.onchange=()=>updateCaptureReview(record.id,{review:review.value}).then(renderLibrary).catch(error);const includeLabel=el('label',undefined,'capture-check'),include=el('input');include.type='checkbox';include.checked=record.included!==false;include.disabled=record.review==='excluded';include.onchange=()=>updateCaptureReview(record.id,{included:include.checked}).catch(error);includeLabel.append(include,document.createTextNode('Include in scan export'));actions.append(review,includeLabel);card.append(actions);
    }
    const detail=el('details'),summary=el('summary','Source and capture details');detail.append(summary,el('p',record.source.url),el('p','Frozen destination at capture: '+[record.context.projectName,record.context.scanName,record.context.subjectName].join(' / '),'micro'),el('p',(record.limitations||[]).join('\n'),'micro'),el('p','Hashes detect changes to saved bytes; they do not establish authenticity or identity.','micro'));card.append(detail);list.append(card);
  }
}
async function refresh(){
  const ticket=++serial,nextState=(await request('workspace.state')).state;if(ticket!==serial)return;state=nextState;let scanId=state.activeScanId,nextSearchId=null;
  if(compact){const tab=(await chrome.tabs.query({active:true,windowId}))[0];tabId=tab?.id;if(tabId){const current=await request('workspace.tabContext',{tabId});scanId=current.context.scanId;nextSearchId=current.context.originatingSearchId||null;}}
  if(ticket!==serial)return;
  const scan=state.scans.find(s=>s.id===scanId);scope={scanId,projectId:scan?.projectId||null};originatingSearchId=nextSearchId;
  const nextValues=await Promise.all([getCaptureSettings(scope.projectId),listSubjects(scope.projectId)]);if(ticket!==serial)return;[settings,subjects]=nextValues;
  const selected=await selectedSubject(scanId);destination.textContent=destinationLabel(state,scanId);subjectLabel.textContent=settings.subjectLabel;subjectSelect.replaceChildren(new Option('Unassigned',''),...subjects.map(s=>new Option(s.name===s.roleId?s.roleId:s.name+' · '+s.roleId,s.id)));subjectSelect.value=selected||'';subjectSelect.disabled=!scope.projectId;
  for(const b of subjectRow.querySelectorAll('button'))b.disabled=!scope.projectId;
  controls.hidden=!compact;refDetails.hidden=!compact;launch.disabled=!tabId;
  reference.replaceChildren(new Option('No saved finding',''));for(const item of state.items.filter(i=>i.projectId===scope.projectId&&['account','source'].includes(i.kind))){const o=new Option(item.title,item.id);o.dataset.kind=item.kind;reference.append(o);}
  if(!compact){notice.textContent='Capture from Gather’s toolbar or side panel. The subject chosen here is reused for this scan.';autoExport.checked=settings.automaticExport;filterSubject.replaceChildren(new Option('Unassigned',''),...subjects.map(s=>new Option(s.name===s.roleId?s.roleId:s.name+' · '+s.roleId,s.id)));if(!subjects.some(s=>s.id===subjectFilter))subjectFilter=null;filterSubject.value=subjectFilter||'';const stats=await captureStats();usage.textContent=(stats.bytes/1048576).toFixed(1)+' / '+(stats.limitBytes/1048576)+' MiB in Gather capture storage. Browser storage can be cleared or evicted; keep image backups.';await renderLibrary();}
}
function schedule(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(error),50);}
async function init(){if(!globalThis.chrome?.runtime?.id)return;windowId=(await chrome.windows.getCurrent()).id;chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[WORKSPACE_KEY]||area==='session'&&(changes['gather.tabContexts.v1']||changes['gather.hideFriendlyLabels']||Object.keys(changes).some(k=>k.startsWith('gather.case.'))))schedule();});if(compact)chrome.tabs.onActivated.addListener(schedule);window.addEventListener('focus',schedule);document.addEventListener('gather:captures-changed',schedule);if(globalThis.BroadcastChannel){const channel=new BroadcastChannel('gather-captures');channel.onmessage=schedule;window.addEventListener('pagehide',()=>channel.close());}const lock=(await chrome.storage.session.get('gather.captureLock'))['gather.captureLock'];let activeIds=[];if(lock){try{await chrome.windows.get(lock.windowId);activeIds=[lock.launchId];}catch{}}await recoverInterruptedCaptures({olderThan:Date.now(),activeIds});await refresh();}
init().catch(error);
